### ISSUE TITLE
 I want to use to see my wallet information on bitfinex 

### ISSUE THREAD

**Issue by stone89son** [JKorf/Bitfinex.Net#1]
Hello.
Thank You have developed this library, Now I want to use to see my wallet information on bitfinex how to do?
I looked in the test folder and did not see an example of that.

Thank you.

Son.

**Comment by JKorf** [comment]
Hi, first set your API credentials as default for new clients
````C#
BitfinexClient.SetDefaultOptions(new BitfinexClientOptions(){
    ApiCredentials = new ApiCredentials("APIKEY", "APISECRET")
});
````
then create a new client and request your wallet info:
````C#
using(var client = new BitfinexClient())
{
    var walletResult = client.GetWallets();
    if(!walletResult.Success)
       Console.WriteLine("Error: " + walletResult.Error);
    else
    {
        foreach(var wallet in walletResult.Data)
            Console.WriteLine(wallet.Currency + ": " + wallet.Balance);
    }
}
````
I have yet to add some examples for the library.

**Comment by stone89son** [comment]
@JKorf  Thank you.
