### ISSUE TITLE
Seems SubscribeToWalletUpdates and SubscribeToTradingUpdates don't work

### ISSUE THREAD

**Issue by SergeevGregory** [JKorf/Bitfinex.Net#101]
Dear developer,
I am try to catch wallet update and trading events by WS. But It seems SubscribeToWalletUpdates and SubscribeToTradingUpdates don't fire never...

**Comment by JKorf** [comment]
Hi, thanks for the report. I've found the bug and it should be fixed in the version I just pushed (should be available in a few minutes)
