### ISSUE TITLE
SubscribeToTradingUpdates don't work

### ISSUE THREAD

**Issue by sndnnlfhvk** [JKorf/Bitfinex.Net#102]
SubscribeToTradingUpdates don't work when using WebSocket. WebSocket cant't revieve any message when new order created or  uplated。
When I use BitfinexClient.GetActiveOrders() ,I can get  newly created active orders。But I want to get  order info  realtime when order created/completed/canceled...  using WebSocket  with ApiCredentials.

**Comment by JKorf** [comment]
Hi, thanks for the report. I've found the bug and it should be fixed in the version I just pushed (should be available in a few minutes)

**Comment by sndnnlfhvk** [comment]
Many thanks。
