### ISSUE TITLE
Deserialize JsonReaderException in "GetClosedOrdersAsync () and GetOpenOrdersAsync()"

### ISSUE THREAD

**Issue by ewrdietsch** [JKorf/Bitfinex.Net#103]
Hi,
I am receiving an exception when I call **"GetClosedOrdersAsync () and GetOpenOrdersAsync()"**, the data received is fine, but the debugger registers the exception **"JsonReaderException"**.

Here the call to **"GetClosedOrdersAsync ()"**:

- _WebCallResult <IEnumerable <BittrexOrderV3>> _Orders = await bittrexClientV3.GetClosedOrdersAsync ();_

Here the exception **"JsonReaderException"** in the data received and is as follows:

- _2019/11/26 00: 24: 04: 568 | Error | Deserialize JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0., LinePosition: 0. Data: error code: 1015_

**Comment by JKorf** [comment]
Hi,
I'm assuming we're talking about Bittrex instead of Bitfinex, but that's okay. I don't have any errors in the output when requesting closed orders. You're saying the data you get in the result is fine but still get an exception in the output?

**Comment by JKorf** [comment]
I see the same question is also asked in the Bittrex repo, so I'll close this and we'll continue from there.
