### ISSUE TITLE
apikey : invalid issue

### ISSUE THREAD

**Issue by EruthiaRaj** [JKorf/Bitfinex.Net#108]
I have create new API key and assigned all the required permission to it.
But when try to  make any authenthicate API call, it prompt "10100:apikey:invalid" error.
Need help to resolve this issue. Below how is my code look likes:

`string apiKey = "XXXxxx"; // here I hv assign actual apikey and secretkey
string secretKey = "XXXXXx"; 
 
BitfinexClient.SetDefaultOptions(new BitfinexClientOptions()
{
	ApiCredentials = new ApiCredentials(apiKey, secretKey),
	LogVerbosity = LogVerbosity.Debug,
	LogWriters = new List<TextWriter> { Console.Out }
});

bitfinexClient = new BitfinexClient();
var balanceInfo = bitfinexClient.GetBalances();`

**Comment by JKorf** [comment]
Hi, that should work. I've pasted your code in a simple test project with my own keys and it successfully retrieves the balances. Can you double check the key and secret are correct?

**Comment by EruthiaRaj** [comment]
Hi, its working now.Thanks for the reply.


 

    On Wednesday, February 5, 2020, 6:32:21 PM GMT+8, Jan Korf <notifications@github.com> wrote:  
 
 
Hi, that should work. I've pasted your code in a simple test project with my own keys and it successfully retrieves the balances. Can you double check the key and secret are correct?
