### ISSUE TITLE
Application freezes when an authenticated method is called

### ISSUE THREAD

**Issue by alexemme** [JKorf/Bitfinex.Net#11]
i'm doing some tests with my application, 

when i set the api credentials, and call, for istance, GetWalletsAsync() 
the entire application hangs and get stuck,
i noticed it worked fine just the first time.

apparently it get stucks on this line : 
`using (var stream = request.GetRequestStream().Result)`
on BitfinexClient.cs , line 852

i checked my api key on the website and it seems to be working fine.

the code is the same you provided:

```
BitfinexClient.SetDefaultOptions(new BitfinexClientOptions(){
    ApiCredentials = new ApiCredentials("APIKEY", "APISECRET")
});
using(var client = new BitfinexClient())
{
    var walletResult = client.GetWallets();
    if(!walletResult.Success)
       Console.WriteLine("Error: " + walletResult.Error);
    else
    {
        foreach(var wallet in walletResult.Data)
            Console.WriteLine(wallet.Currency + ": " + wallet.Balance);
    }
}
```

please help me, what i have to check?

**Comment by JKorf** [comment]
Hi,
I assume the freeze happens because you are calling it from the UI-thread. You can fix this by wrapping the code in a task:
````C#
Task.Run(()=>{
    // Code
});
````

Note that this is a little bug on the library side and it will be fixed in the next release, after which the separate task isn't needed anymore

**Comment by JKorf** [comment]
Released a new version, should be fixed there. Let me know if you have any issues.

**Comment by alexemme** [comment]
Yes, it works fine now,

thank you
