### ISSUE TITLE
Count and Price mixed Up When Getting Order Book

### ISSUE THREAD

**Issue by Hawxkz** [JKorf/Bitfinex.Net#111]
Hello,

im have the issue that the Value of Price and Count is mixed up when im Trying to get the OrderBook. 

> await apiClient.GetOrderBookAsync("tBTCUSD", Bitfinex.Net.Objects.Precision.R0);

This is the Call i used

**Comment by JKorf** [comment]
Fixed in the latest version. This was only an issue with Precision.R0 which retrieves the raw order book instead of the aggregated order book. I've added a new method for the raw order book GetRawOrderBook for this.
