### ISSUE TITLE
Got "Error deserializing data" for getting "Fill or Kill" type order

### ISSUE THREAD

**Issue by W0dahs** [JKorf/Bitfinex.Net#112]
After I placed order with `OrderTypeV1.ExchangeFillOrKill`, then get the order status with id:
```
var res = await client.GetOrderAsync(id);
if (!res.Success)    //  <--- always false
{
    throw new Exception(string.Format("Failed to get order (ID: {0} Symbol: {1})", id, symbol));
}
```
The `res.Success` always false with message "Error deserializing data" return.
It seems there is deserializing issue for "Fill or Kill" type order.

**Comment by JKorf** [comment]
Should be fixed
