### ISSUE TITLE
 Message not handled Debug log

### ISSUE THREAD

**Issue by Hawxkz** [JKorf/Bitfinex.Net#114]
When i use to SubscribeToWalletUpdates everytime the Websocket gets an Update i get an debug log which says "Message not handled". 

I search around and i think this error is located in the CryptoExchange.Net SocketConnection.cs in the function ProcessMessage. In my case it was on Line 165 where the log whould be written

**Comment by JKorf** [comment]
It this still an issue? If so, could you paste a debug log output of the messages?

**Comment by Hawxkz** [comment]
It is not an issue anymore. Thank you.
