### ISSUE TITLE
OCO Order + AffiliateCode

### ISSUE THREAD

**Issue by robotech-capital** [JKorf/Bitfinex.Net#116]
```
string symbol = "BTCUSD";
decimal amount = 0.00555309;
decimal price = 11513.667663400960710369074987;
decimal ocoSellPrice = 9181.966687165310710369074987;
string affiliateCode = "-mr4QNVOE";

Bitfinex.Net.BitfinexClient.PlaceOrder(
symbol: symbol,
side: OrderSide.Sell.,
type: OrderTypeV1.Limit,
amount: amount,
price: price,
ocoOrder: true,
ocoSellPrice: ocoSellPrice,
affiliateCode: affiliateCode);
```

I receive an error and the WebCallResult<BitfinexPlacedOrder> returns:
`{-1: Key sell_price_oco should be a decimal string. }`

WebSocket method is working perfectly, I can place an OCO Order without any problem (but then I cannot insert my affiliateCode on a WebSocket Order)

On the other side, I can insert my affiliateCode on a REST Order, but it is not working for OCO Orders

Can you kindly help me here? Also, adding the affiliateCode on WebSocket Orders would be much appreciated too. Congratulations for your work, btw!

**Comment by JKorf** [comment]
Hi, I've fixed both methods. There was a serialization issue on the rest API which meant the sell/buy_price_oco was sent as decimal instead of string as expected by Bitfinex. 
I've also added the affiliateCode parameter to the socket client place order method.
