### ISSUE TITLE
No Trades being received when subscribing to multiple symbols

### ISSUE THREAD

**Issue by Taats** [JKorf/Bitfinex.Net#118]
Hi. 

Im fetching all symbols from bitfinex (around 300) of them and when I then use the BitfinexSocketClient to connect to all of them then im getting zero responses. Even when I use 12 clients each containing 29 subscribtions the whole thing just locks up and drops connections. 

How should i tackle this problem? 

Kind regards,

Thomas

**Comment by JKorf** [comment]
Hi, I've pushed a fix for the socket client, which caused it to open a new socket connection for each subscription. Can you try it again with the latest version to see if that helps? You can control how many subscriptions will be combined on a single connection with the SocketCombineTarget property in the socket client options. It defaults to 10, but you could maybe up that.

**Comment by JKorf** [comment]
I'm assuming this has been fixed. If not, let me know.
