### ISSUE TITLE
SubscribeToOrderUpdates method deleted?

### ISSUE THREAD

**Issue by capponMatteo** [JKorf/Bitfinex.Net#119]
Hi, I have an old trading bot based on version 1.2.4 of this libray, but I have recently updated it to the latest version.
The method `SubscribeToOrderUpdates` is no longer available on instances of the `BitfinexSocketClient` class.
Has the method been deleted or has it just changed name?
Or is there a new and better way to get real time order updates and fills?

Thanks for your time and work.

**Comment by JKorf** [comment]
Hi, sorry for the late response, must have missed the notification. The user order updates are now part of the `SubscribeToTradingUpdatesAsync` method.

**Comment by capponMatteo** [comment]
Got it now, thank you very much 😁
