### ISSUE TITLE
Getting balances not working, method not found

### ISSUE THREAD

**Issue by GiganteX** [JKorf/Bitfinex.Net#123]
I tried this with Binance.NET, worked fine, then I tried with Bitfinex.NET, initialized the client the same way. Called client.GetBalances() (instead of client.General.GetAccountInfo() as it's called in Binance.NET) but I'm getting the method not found exception, see attached screenshot for details. I'm guessing I'm missing something obvious, I just don't know what...

![Capture](https://user-images.githubusercontent.com/15637533/104398205-95903c80-554e-11eb-8c05-812ee312b1b0.PNG)

**Comment by dante1989** [comment]
You have the same problem like me. After updating the newest CryptoExchange.Net. Binance.NET is still working well but Biftinex.NET can not work anymore

**Comment by JKorf** [comment]
Hi, sorry this was an issue in versioning. Binance.Net was using a newer version of the CryptoExchange.Net library than the other exchange libraries. I've updated those now to the latest version, so after getting the latest version (can take a few minutes to show up on nuget) of each implementation it should work again.

**Comment by GiganteX** [comment]
Ah, ok! Thanks for the quick fix!! :)

**Comment by GiganteX** [comment]
Just a verification: It worked nicely! Thanks!
