### ISSUE TITLE
Orders History: Symbol is optional

### ISSUE THREAD

**Issue by TomasMichal** [JKorf/Bitfinex.Net#124]
https://docs.bitfinex.com/reference#rest-auth-orders-history

In endpoint /v2/auth/r/orders/Symbol/hist is parametr Symbol optional, but in Bitfinex.Net is required. Therefore, it is not possible to get whole orders history.

**Comment by JKorf** [comment]
Hi, I wasn't aware that the parameter was optional. I've pushed version 3.3.0 which in which the parameter is optional. Also made the parameter optional for the GetTradesHistory and GetLedgerHistory endpoints.

**Comment by TomasMichal** [comment]
Hi, thank you very much :)
