### ISSUE TITLE
CryptoExchange.Net.Interfaces.IWebsocket Not found

### ISSUE THREAD

**Issue by andrzej-suwala** [JKorf/Bitfinex.Net#13]
Hi,

After upgrading CryptoExchange.Net to 0.0.23
WebSocket stopped working, throwing 

> System.MissingMethodException: 'Method not found: 'CryptoExchange.Net.Interfaces.IWebsocket CryptoExchange.Net.Interfaces.IWebsocketFactory.CreateWebsocket(System.String)'.'

This throws only on .net 4.7, on .net core it's working as usual.

Same on 0.0.22.
0.0.21 is ok.

**Comment by JKorf** [comment]
Bitfinex.Net is hard linked to a CryptoExchange.Net version, if you upgrade CryptoExchange.Net independently you get error like this. I'll update Bitfinex.Net soon, waiting for more info on #12 to fix that as well for next release.

**Comment by andrzej-suwala** [comment]
Ok, thanks :)

**Comment by JKorf** [comment]
No problem, thanks for reporting issues you find :)
