### ISSUE TITLE
BUG in IExchangeClient.GetOrderBookAsync ASKS/BIDS

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Bitfinex.Net#132]
ASKS/BIDS they have different interpretations based on whether we are trading or founding 

see https://docs.bitfinex.com/reference#rest-public-book

![image](https://user-images.githubusercontent.com/6449169/116126825-5fbf3000-a6c7-11eb-969b-d6ac639be922.png)

so the following code is correct only in case founding in trading is incorrect, asks / bids are reversed

```
 var result = new BitfinexOrderBook
            {
                Asks = orderBookResult.Data.Where(d => d.Quantity > 0),
                Bids = orderBookResult.Data.Where(d => d.Quantity < 0)
            };
```

**Comment by JKorf** [comment]
Fixed in the latest version
