### ISSUE TITLE
SymbolOrderBook connection unstable when subscribing to many Symbols

### ISSUE THREAD

**Issue by PsykotropyK** [JKorf/Bitfinex.Net#134]
**Describe the bug**

1.  when subscribing to 1 Symbol, the OrderBook sync easily and remain synced without any reconnection attemps
2.  when I add some symbols (let's say 10) I have : 
 * if I use default SocketClient (i.e. not specifying any option in BitfinexSymbolOrderBook) connection can be very unstable on some Symbols, having many OnStatusChange events (`OrderBookStatus.Reconnecting` <> `OrderBookStatus.Synced`). On the other hand some Symbol are synced and stable
 * if i us a SocketClient shared among all instances of BitfinexSymbolOrderBook the stream seems to pause at the first reconnection attempts, i.e. some Symbols go from "Synced" to "Reconnecting" and then nothing else happens for a while and suddenly I have a few updates (i.e. some goes from reconnecting to sync other the other way, with very few OrderBook having received new updates
3. if I subscribe to many symbols (100) I have :
 * with default SocketClient : only ~15 Symbols manage to sync, with the same instability as described above
 * with shared SocketClient, 15/20% remains under "Connecting" status, most are always under "Reconnecting". The Synced one got order book updates. Also, on some run, everything stops (i.e. no more book updates, nor status updates) without anything logged nor exception raised

Moreover, when trying to connect, the Symbols goes from "Disconnected" to "Connecting" one after another, and hangs at "Connecting" until they are all under this state (which takes a while for 100)

**To Reproduce**
*Client* : Client = new BitfinexClient(new BitfinexClientOptions() { LogLevel = LogLevel.Debug, ApiCredentials = new ApiCredentials("key", "secret") });
*Socket* : SocketClient = new BitfinexSocketClient();
*OrderBookOptions* : Options = new BitfinexOrderBookOptions(SocketClient);
*OrderBook*
 * new BitfinexSymbolOrderBook(symbol.Name, Precision.PrecisionLevel0, 25);
 * new BitfinexSymbolOrderBook(symbol.Name, Precision.PrecisionLevel0, 25, Options);

I monitor the behavior by bindgin a custom class to a ListBox having 3 properties bound: Name (name of the Symbol) Status (connection status) and Count (number of time OnOrderBookUpdate was triggered).

See the attached Project for the complete implementation
[ProjectTester.zip](https://github.com/JKorf/Bitfinex.Net/files/7006453/ProjectTester.zip)

**Expected behavior**
Lack of stability may not come from your code but from the API, though it should be checked
Socket should be able to resync 
If using the default SocketClient is not recommended, defaulting it should not be possible

**Debug logging**
The log (Trace) with 100 symbols and a single SocketClient shared is attached as .txt.
Some stats on the log:
Out of 814 log lines : 
 * 415 Warnings (251 out of sync, 99 checksum error, 65 connection lost)
 * 398 Info (linked to connection and status updates)
No apparent errors

[logs.txt](https://github.com/JKorf/Bitfinex.Net/files/7006635/logs.txt)

**Comment by JKorf** [comment]
I found an issue with the checksum calculation. When calculating our local checksum a small decimal like 0.0000012 is written as 1.2E-06, which makes the checksum string invalid. I'm looking into a solution for this, decimal handling in Json.Net and json in general is a bit of a pain

**Comment by PsykotropyK** [comment]
If I follow you, the checksum issue makes that it thinks the order book is unsynced, and forces to resync. That would explain the lack of stability, but not why it can't resync. Or is it then on the broker's side that the high amount of request bans my ip?

**Comment by PsykotropyK** [comment]
@JKorf I understand that the checksum happens [here](https://github.com/JKorf/Bitfinex.Net/blob/master/Bitfinex.Net/BitfinexSymbolOrderBook.cs) in the `protected override bool DoChecksum(int checksum)` method.

You have 
    for (var i = 0; i < 25; i++)
        {
            if (bids.Count >= i)
            {
                var bid = (BitfinexOrderBookEntry)bids.ElementAt(i).Value;
                checksumValues.Add(bid.RawPrice);
                checksumValues.Add(bid.RawQuantity);
            }
            if (asks.Count >= i)
            {
                var ask = (BitfinexOrderBookEntry)asks.ElementAt(i).Value;
                checksumValues.Add(ask.RawPrice);
                checksumValues.Add(ask.RawQuantity);
            }
        }

Myabe using something like `String.Format("{0:F20}", [value]);` can help? As seen [here](https://stackoverflow.com/questions/1319191/how-to-convert-double-to-string-without-the-power-to-10-representation-e-05)

**Comment by JKorf** [comment]
Hi, I've done a fair amount of testing and released a new version with various fixes for the checksum validation, and also improved stability/speed on the socket connections. Can you have another go with the latest version?

**Comment by PsykotropyK** [comment]
I updated and run, the result is great. I'll test more in depth later but running it shows as expected results. 96 out of 100 are connected and synced, remaining 4 stay disconnected. But that's not an issue, I'll have to check them specifically, it can be due to many things. 

I keep the ticket open in case I find something later on, but it seems fully fixed. I'll close it in a couple of days.
