### ISSUE TITLE
Keep Funding function

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Bitfinex.Net#137]
I did not find the Keep Funding function in the library. Is it implemented?

**Comment by JKorf** [comment]
Hi, no it is currently not implemented. The Bitfinex implementation needs an update. I'll add it in soon

**Comment by JKorf** [comment]
Has been implemented

**Comment by Captain12311** [comment]
Any update when bitfinex.net will be working again?

Todd

**Comment by fieldfoxWim** [comment]
@Captain12311  What 's not working for you?

**Comment by Captain12311** [comment]
I can't find the site...

Bitfinex.net

Send me a Link for it.

Todd

**Comment by fieldfoxWim** [comment]
If you mean the exchange it is https://www.bitfinex.com/
(the .net site does redirect though)

the .Net in the repo name is related to the programming framework used...

**Comment by Captain12311** [comment]
Sorry, I keep seeing Bitfinex.net in your subject line. .Net and .Com
sites/Companies are NOT connected.

I invested in Bitfinex.net and I'm trying to login into that site.

So, Am I correct?

Todd

**Comment by Captain12311** [comment]
Sorry, I keep seeing Bitfinex.net in your subject line. .Net and .Com
sites/Companies are NOT connected.

I invested in Bitfinex.net and I'm trying to login into that site.

So, Am I correct?


Todd



Todd
