### ISSUE TITLE
[Feature-request] Post-order

### ISSUE THREAD

**Issue by Espleth** [JKorf/Bitfinex.Net#14]
Hi, can you please add post-order option for placing order?
https://support.bitfinex.com/hc/en-us/articles/115003507365-Post-Only-Limit-Order-Option
Here's a description on it.

**Comment by JKorf** [comment]
Hi,
In the latest version I've added the optional parameters the API offers to the request, one of which is the postOnly boolean, enjoy ^^

**Comment by Espleth** [comment]
Works good for me, thanks!

Just a small note (or feature?), i'm not sure if this can be fixed:

`var order = await client.PlaceOrderAsync("BTCUSD", OrderSide.Buy, OrderTypeV1.Limit, 0.002m, 10000, postOnly: true);
Console.WriteLine(order.Data.Canceled); // false, in debug "is_cancelled": false, "is_live": true
order = await client.GetOrderAsync(order.Data.Id);
Console.WriteLine(order.Data.Canceled); // true, "is_cancelled": true, "is_live": false`

**Comment by JKorf** [comment]
No sorry, that's not something I can fix, that's just how the Bitfinex API works.
