### ISSUE TITLE
Error on wallet transfer

### ISSUE THREAD

**Issue by JCloarec** [JKorf/Bitfinex.Net#143]
I'm getting a "400: Key currency was not present" when trying to transfer assets between exchange and margin wallets.
It looks like the transfer request is sending an "asset" parameter when the bitfinex api is expecting a "currency" parameter as per their documentation (https://docs.bitfinex.com/v1/reference#rest-auth-transfer-between-wallets)

**Comment by JKorf** [comment]
Thanks, I've fixed the parameter name in the latest version
