### ISSUE TITLE
Deserialization exception after the call ClosePositionAsync

### ISSUE THREAD

**Issue by egorkrivtsov** [JKorf/Bitfinex.Net#144]
**Describe the bug**
Version: 5.0.6
After calling _apiClient.SpotApi.Trading.ClosePositionAsync(..) the position is closed but I get the exception which, I think, belongs to deserialization the reposnse.
Bitfinex   | [9] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'order.price', line 1, position 302

**To Reproduce**
Try to close the position

**Debug logging**
Trace:
fail: Bitfinex.Net.Clients.BitfinexClient[0]
      Bitfinex   | [9] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'order.price', line 1, position 302. data: {
        "message": "Submitting a market order to liquidate this position.",
        "order": {
          "id": 90690955927,
          "type": "MARKET",
          "pair": "YFIUSD",
          "status": "ACTIVE (note:POSCLOSE)",
          "created_at": "2022-04-01T08:26:17.582683+03:00",
          "updated_at": "2022-04-01T08:26:17.582683+03:00",
          "user_id": 2317173,
          "amount": "0.001",
          "price": null,
          "originalamount": "0.001",
          "routing": "",
          "lockedperiod": null,
          "trailingprice": "0.0",
          "hidden": false,
          "vir": 1,
          "maxrate": "0.0",
          "placed_id": null,
          "placed_trades": null,
          "nopayback": null,
          "avg_price": "0.0",
          "active": 2,
          "fiat_currency": null,
          "cid": null,
          "cid_date": null,
          "mseq": 0,
          "gid": null,
          "flags": 0,
          "price_aux_limit": "0.0",
          "type_prev": null,
          "tif": null,
          "v_pair": "YFIUSD",
          "meta": null,
          "liq_stage": null,
          "pos_id": null
        },
        "position": {
          "id": 153024588,
          "pair": "YFIUSD",
          "status": "ACTIVE",
          "user_id": 2317173,
          "created_at": "2022-04-01T08:26:17+03:00",
          "updated_at": "2022-04-01T08:26:17+03:00",
          "amount": "-0.001",
          "base": "22263.0",
          "swap": "0.0",
          "noliquidation": null,
          "period": null,
          "vir": 1,
          "maxrate": "0.0",
          "swap_type": 0,
          "active": 1,
          "type": 0,
          "lev": 0,
          "stage": 0,
          "collateral": "0.0",
          "meta": "{\"reason\": \"TRADE\", \"order_id\": 90633339719, \"liq_stage\": null, \"order_cid\": 19586649, \"order_gid\": null, \"trade_price\": \"22263.0\", \"trade_amount\": \"-0.001\", \"user_id_oppo\": 2509968, \"order_id_oppo\": 90690948876}"
        }
      }

**Comment by JKorf** [comment]
Thanks for the report, this should be fixed in the latest version
