### ISSUE TITLE
OrderBook

### ISSUE THREAD

**Issue by GilbertoTheMighty** [JKorf/Bitfinex.Net#145]
Hello. Is there a way to switch `BitfinexSymbolOrderBook` to raw mode? By default it show only 25 levels and can be extended to 100, but anyways maximum available precision is 0. I would like to have something like `BinanceSpotSymbolOrderBook` that aggregates everything. Thanks.

**Comment by GilbertoTheMighty** [comment]
`Task<CallResult<UpdateSubscription>> SubscribeToOrderBookUpdatesAsync`

Supports only 25 and 100 depth. Bitfinex says it can also be 1 and 250 https://docs.bitfinex.com/reference#ws-public-books

**Comment by kulikov-dev** [comment]
@JKorf As I see in code, this issues were solved and have to be closed?

**Comment by JKorf** [comment]
Correct, this has been fixed
