### ISSUE TITLE
WalletTransfer always successful

### ISSUE THREAD

**Issue by JCloarec** [JKorf/Bitfinex.Net#147]
The WalletTransfer method always returns a success, even when there was an error.

I tried sending an amount above my current balance, and I received a success result with a message "Cannot complete transfer. Exchange balance insufficient".
Same thing when I tried to transfer an asset not available in Margin: I get a success result, with a message "SAND cannot be used for Margin Trading. Transfer to Margin wallet not possible."

**Comment by JKorf** [comment]
This has been fixed in the latest version
