### ISSUE TITLE
PlaceOrderAsync for REST x WebSocket (missing overloads on WebSocket - cancelTime is critical)

### ISSUE THREAD

**Issue by RobotecX** [JKorf/Bitfinex.Net#148]
First of all, thank you for your work and dedication!

**Describe the bug**
PlaceOrderAsync method for REST and WebSocket has different overloads and different functionalities. Most critical is the absence of the [DateTime? cancelTime] overload in the WebSocket version

**Expected behavior**
WebSocket is a better option when placing multiple orders at the same time since API limitations are better when using authenticated WebSocket instead of REST

But, for now, REST has a much more complete version of the PlaceOrderAsync method:

**REST PlaceOrderAsync:**
```
namespace Bitfinex.Net.Interfaces.Clients.SpotApi;
public interface IBitfinexClientSpotApiTrading

Task<WebCallResult<BitfinexWriteResult<BitfinexOrder>>> PlaceOrderAsync(
    string symbol,
    OrderSide side,
    OrderType type,
    decimal quantity,
    decimal price,
    int? flags = null,
    int? leverage = null,
    int? groupId = null,
    int? clientOrderId = null,
    decimal? priceTrailing = null,
    decimal? priceAuxLimit = null,
    decimal? priceOcoStop = null,
    DateTime? cancelTime = null,
    string? affiliateCode = null,
    CancellationToken ct = default);
```

**WebSocket PlaceOrderAsync: missing overloads marked with (x)**
```
namespace Bitfinex.Net.Interfaces.Clients.SpotApi
public interface IBitfinexSocketClientSpotStreams : ISocketApiClient, IDisposable

Task<CallResult<BitfinexOrder>> PlaceOrderAsync(
    string symbol,
(x) OrderSide side,
    OrderType type,
    decimal quantity,
    decimal? price = null,
    OrderFlags? flags = null,
(x) int? leverage = null,
    long? groupId = null,
    long? clientOrderId = null,
    decimal? priceTrailing = null,
    decimal? priceAuxiliaryLimit = null,
    decimal? priceOcoStop = null,
(x) DateTime? cancelTime = null,
    string? affiliateCode = null);
(x) CancellationToken ct = default);
```

**Missing Overloads/Functionalities on WebSocket (critical: DateTime? cancelTime)**
I've listed below 4 missing overloads:
- (x) OrderSide side,
- (x) int? leverage = null,
- (x) DateTime? cancelTime = null,
- (x) CancellationToken ct = default,

Please let me know if I can help you with any test

**Comment by JKorf** [comment]
Hi, I've added the parameters in the latest version, except for the cancellation token. Let me know if you have any other issues
