### ISSUE TITLE
enum OrderFlags | missing values (critical: ReduceOnly)

### ISSUE THREAD

**Issue by RobotecX** [JKorf/Bitfinex.Net#149]
**Bitfinex OrderFlags**
Currently, Bitfinex have 7 flag-values for new orders:
- Default = 0,
- Hidden = 64,
- Close = 512,
- ReduceOnly = 1_024,
- PostOnly = 4_096,
- OCO = 16_384,
- NoVarRates = 524_288,

**Project OrderFlags**
Currently, the project has the following flags:
```
using System;
namespace Bitfinex.Net.Enums
{
public enum OrderFlags
    {
        Hidden = 64,
        Close = 512,
        PostOnly = 4096,
        OneCancelsOther = 16384
    }
}
```

**3 Missing OrderFlags (critical: ReduceOnly)**
Please find below the missing OrderFlags:
- Default = 0,
- ReduceOnly = 1_024,
- NoVarRates = 524_288,

**Comment by JKorf** [comment]
Thanks for the report, I've added the missing values in the latest version

**Comment by RobotecX** [comment]
Thanks! I've noticed 2 things on the last update:

--
--
1. The int value for ReduceOnly is missing:
```
using System;

namespace Bitfinex.Net.Enums
{
    [Flags]
    public enum OrderFlags
    {
        Hidden = 64,
        Close = 512,
        ReduceOnly,
        PostOnly = 4096,
        OneCancelsOther = 16384,
        NoVarRates = 524288
    }
}
```
From https://docs.bitfinex.com/docs/flag-values
ReduceOnly = 1024

--
--
2. Currently, the Multiple Flags option form placing new orders in WebSocket is disabled - you may sum flag values to pass multiple flags. For example passing 4160 (64 + 4096) means Hidden + PostOnly

I've created a simple method that solves this:
```
public static int GetHashCode(IEnumerable<OrderFlags> orderFlags)
{
    return orderFlags.Sum(selector: x => x.GetHashCode());
}
```

For this to work properly,
(i) the overload for the PlaceOrderAsync() WebSocket method (in namespace Bitfinex.Net.Interfaces.Clients.SpotApi) should be an array of OrderFlags (instead of a single value of the OrderFlags enum), and
(ii) use the GetHashCode method to return the int value that results in the Multiple Flags option

Currently, the PlaceOrderAsync() REST method in Bitfinex.Net.Interfaces.Clients.SpotApi works perfectly, since the flags overload is an int (and you can combine the values for each flag in any way)

**Comment by RobotecX** [comment]
(I'll post it as a new issue since this one is closed)
