### ISSUE TITLE
Error deserializing data exception

### ISSUE THREAD

**Issue by Espleth** [JKorf/Bitfinex.Net#15]
Hi, I think something has changed in the Bitfinex API, I started getting these errors. I tried 1.0.3 and 1.0.5 - same result.
Here's simple example:
```
var result = await client.GetOrderHistoryAsync("tIOTUSD");
if (!result.Success)
{
    Console.WriteLine("Error: " + result.Error.Code + "\n" + result.Error.Message);
}
```
```
Error: 4
Error deserializing data: Deserialize Unknown Exception: Sequence contains no matching element. Received data: [[11834800778,null,83768609087,"tIOTUSD",1525734969000,1525734968000,10,10,"LIMIT",null,null,null,null,"POSTONLY CANCELED",null,null,2.4,0,0,0,null,null,null,0,0,null,null,null,null,null,null,null]]
```

**Comment by Espleth** [comment]
I just checked another data without POSTONLY CANCELED orders, and it worked. So, I think this is the problem. 
Also, it's reproduced with FILLORKILL CANCELED as well.

**Comment by JKorf** [comment]
Hi, thanks for reporting this. It should be fixed in the new release.

**Comment by Espleth** [comment]
Works good, thanks.
