### ISSUE TITLE
Symbol Precision not available in v7

### ISSUE THREAD

**Issue by rakewell** [JKorf/Bitfinex.Net#153]
hi on v6 BitfinexSymbolInfo we had PricePrecision, can someone tell me where this had gone in v7?

**Comment by JKorf** [comment]
Hi, this was returned in the V1 bitfinex API endpoints, but not in the V2 api. However, with the V1 API it always returned '5', so it seems they just omitted it from the API. However, from the docs it still the same:

Price Precision
The precision level of all trading prices is based on significant figures. All pairs on Bitfinex use up to 5 significant digits and up to 8 decimals (e.g. 1.2345, 123.45, 1234.5, 0.00012345). Prices submit with a precision larger than 5 will be cut by the API.

**Comment by Captain12311** [comment]
What does this mean in simple terms for me. I know what api is but that's
limited

Todd
