### ISSUE TITLE
Possible to subscribe to BalanceInfo web socket handler

### ISSUE THREAD

**Issue by rakewell** [JKorf/Bitfinex.Net#154]
Hello,

would it be possible to extend the web socket portion of the application to support the BalanceInfo event:

https://docs.bitfinex.com/reference/ws-auth-balance-info

I see that you support Wallet Updates ("wu") but I can't see any support for Balance Info ("bu") subscriptions. You support it in the web socket handler: 

`new BitfinexEvent("bu", BitfinexEventType.BalanceUpdate, "Balance", true),`

There's also a bit of confusion around the naming convention: the `SubscribeToBalanceUpdatesAsync `method is really subscribing to WalletUpdates: 

```
    var tokenHandler = new Action<DataEvent<JToken>>(tokenData =>
    {
        HandleAuthUpdate(tokenData, walletHandler, "Wallet");
    });

```
This could be renamed to `SubscribeToWalletUpdatesAsync `but would then clash with adding a new method for Balance updates. Perhaps `SubscribeToBalanceInfoUpdatesAsync `would avoid confusion

**Comment by JKorf** [comment]
This is possible with the latest versions
