### ISSUE TITLE
Could you add GetSymbols and GetSymbolDetails method from v1 API?

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#17]
https://bitfinex.readme.io/v1/reference#rest-public-symbols
https://bitfinex.readme.io/v1/reference#rest-public-symbol-details
I haven't found it in v2...

**Comment by JKorf** [comment]
I'm currently on holiday, but I'll add it when I get back.

**Comment by JKorf** [comment]
Hi, this has been added in the latest version (v1.0.9). Sorry for the delay.
