### ISSUE TITLE
WebSocket.PlaceOrder method: ClientOrderID issue

### ISSUE THREAD

**Issue by ciottied** [JKorf/Bitfinex.Net#18]
Hi there.

the BitFinex websocket client PlaceOrder method accepts the parameter `string clientOrderId` .
The `BItfinexOrder`  class defines the same parameter as `int64/long`.
The V2 websock BitFinex API New Order wants` int45` in the parameter cid (unique in the day).
Rest API wants a `int.` 

If in this method : 

` var placeResult = Bcl.PlaceOrder(OrderType.ExchangeStop, symbol: Ord.Symbol, amount: Ord.Amount, clientOrderId: Ord.ClientOrderId.ToString(), price: Ord.Price);`
where:  Bcl is a `BitfinexSocketClient` and Ord is a `BItfinexOrder` class.

 I pass  `long.ToString`  (value "67358875" got from debug), I receive Server error: cid: invalid.

What's the correct format to pass ?
Is it a Bug ?

Thanks a lot.

**Comment by JKorf** [comment]
I'll look into it when I get back from holiday next week

**Comment by JKorf** [comment]
Hi, it should be long. However it was send as a string value, so Bitfinex rejected it. I've fixed it in the latest version (v1.0.9). Sorry for the delay.

**Comment by ciottied** [comment]
Thank You!

**Comment by ciottied** [comment]
I confirm that problem is solved.
Now I can send a log as clientOrderID to Bitfinex, and it returns in Bitfinex Orders messages.
With one: caveat: 

```
a 18 digits lenght long like 
Datetime.Now.Ticks =         636651138048739722
Is truncated to 16 digits => 636651138048739700

```
Just stay  < 16 digits (now I use 11) and everything is ok.
