### ISSUE TITLE
Cannot install Bitfinex.Net packet in nuget 

### ISSUE THREAD

**Issue by stone89son** [JKorf/Bitfinex.Net#2]
Hi @JKorf  I cannot install Bitfinex.Net packet in nuget 

-I used .Net 4.7
-Window form application
-Visual studio 2015

![cannot](https://user-images.githubusercontent.com/6795515/37186313-2e86afc4-2388-11e8-97a5-8884d4e3a3d6.PNG)

**Comment by JKorf** [comment]
Can you try installing the latest Nuget client for VS 2015 if you don't already have it?
https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by stone89son** [comment]
Thank you
