### ISSUE TITLE
Websocket SubscribeToBookUpdates

### ISSUE THREAD

**Issue by Shipolia** [JKorf/Bitfinex.Net#20]
Hello,
I dont understand correctly how to use the SubscribeToBookUpdates Websocket... and i dont find any example how to use correctly the websockets..

                var options = new BitfinexSocketClientOptions()
                {
                    ApiCredentials = new ApiCredentials(KEY, SECRET)
                };

                var client = new BitfinexSocketClient(options);
                var tickerSub = await client.SubscribeToBookUpdates("tBTCUSD", 0, 0, 10, data =>
                {
                    AppendTextBox("Ticker update");
                });

How i can use now the Orderbook with "Updates" (Price, Amount, Total) in a listbox in a neverending while with resub/reconnecting? 
The other Question, is it better to use multiple Tasks for each Pair or can handle a Task 10 Pairs?
and the last Question, the frequency 0 = realtime updates? (i hope yes)
thank you

**Comment by JKorf** [comment]
Hi, I think you're forgetting to actually start the websocket connection. If you add `client.Start();` at the end it should be okay I think.
The library automatically handles reconnecting/resubbing for you if connection is lost. 

Regarding whether it's better to have multiple tasks or a single task, that depends on the context. If you just want to subscribe to 10 different symbols, then just doing multiple of these is fine:
````C#
    var tickerSub = await client.SubscribeToBookUpdates("tBTCUSD", 0, 0, 10, data =>
            {
                AppendTextBox("Ticker update");
            });
````

For your last question, yes, 0 is mapping to realtime. You could use the enum to make this more clear:
````C#
    var tickerSub = await client.SubscribeToBookUpdates("tBTCUSD", 0, Frequency.Realtime, 10, data =>
            {
                AppendTextBox("Ticker update");
            });
````

**Comment by kingchenc** [comment]
Thank you Jkorf, the last part from your code make sence with the enum"Frequency.Realtime"! :)

But i dont know what im doing wrong, i get a error after Authentication..

2018.06.04 15:51:08:990 | Info | Socket connection established
2018.06.04 15:51:09:419 | Info | Websocket version: 2, platform status: operational
2018.06.04 15:51:09:542 | Info | Authentication successful
2018.06.04 15:51:14:443 | Warning | Failed to sub Bitfinex.Net.Objects.SocketObjects.BookSubscriptionRequest: 3: Server error: No confirmation received

**Comment by Shipolia** [comment]
Thank you Jkorf, the last part from your code with the enum "Frequency.Realtime" make sence :)

But i dont know what im doing wrong, i get always a error warning after Authentication successful...

2018.06.04 15:53:31:176 | Info | Socket connection established
2018.06.04 15:53:31:604 | Info | Websocket version: 2, platform status: operational
2018.06.04 15:53:31:708 | Info | Authentication successful
2018.06.04 15:53:36:630 | Warning | Failed to sub Bitfinex.Net.Objects.SocketObjects.BookSubscriptionRequest: 3: Server error: No confirmation received

**Comment by JKorf** [comment]
If you're having trouble you can try to put the LogVerbosity to Debug, it displays what the server actually returns. Doing so with your code revealed that the limit parameter can only be either 25 or 100, not 10. If you change it 25 it should work.

**Comment by Shipolia** [comment]
Have you please any code snipped for websocket to split buy and sell to two listboxes? :3 
(string test = (string.Format("{0} | {1}", data[0].Price, data[0].Amount));) < this is not the fatest way for every "line" i think, and the code get confusing.

And yes, it was so simple, 25 Limit works great, thx.

**Comment by JKorf** [comment]
I see no mentioning of iceberg anywhere in the API documentation. What is it exactly you want to know?

**Comment by Shipolia** [comment]
Jep, the API doc give no answer to my quesion...

What i mean:

Ticker from Api BTC/USD:  (Websocket the same thing)
Price: 7532.9
Amount: 56.4xxxxx

Book from the Side BTC/USD:
Price: 7532.9
Amount/Total: 8.62xxxx

So, the Amount is so different, missing 48 Bitcoins on the bitfinex side, only the iceberg orders make sence for me on the api, or i missunderstand something?

**Comment by JKorf** [comment]
I see what you mean, I'm not sure why that is. I verified that the data is parsed correctly on the library side, it's just what the bitfinex server returns. You could ask someone @ Bitfinex maybe.

**Comment by Shipolia** [comment]
Allright Thank you Jkorf for the Help, i will make a Ticket to Bitfinex Support... I'll let you know if there is something new with this :)

@JKorf What does this mean: 2018.06.05 17:13:29:064 | Warning | Authentication failed: nonce: small

or here;

2018.06.05 18:03:42:968 | Warning | Authentication failed: nonce: small
2018.06.05 18:03:42:968 | Warning | Authentication failed: nonce: small
2018.06.05 18:03:43:216 | Error | Error in processing loop. System.InvalidOperationException, The Collection was modified; enumeration operation may not execute.., at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.List1.Enumerator.MoveNextRare() at System.Collections.Generic.List1.Enumerator.MoveNext()
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source, Func2 predicate)
at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: [346,[45.807,5634.84840729,45.816,5582.61189205,0.13746556,0.003,45.57879304,255.08086307,45.94957822,44.35917213]]

**Comment by JKorf** [comment]
Regarding the second error you get, I'm adding some locking which should fix that. 

The first issue is that the authenticate message has a Nonce parameter which should always be bigger than the last Nonce it received from you. This is error will be returned if the Nonce isn't bigger than the last one it received. 
You only get that error when you start 2 or more tasks? Could you share that code with me?

Thanks for you feedback so I can make the library better ^^

**Comment by kingchenc** [comment]
@Jkorf  No Problem and Thank you for fixing the second error :)
Maybe that helps you to solve the problem better, error show after this simple code:

                string z = (string.Format("{0}", data[0].BidSize));
                Invoke((Action)delegate { listBox8.Items.Clear(); });
                listBox8.Invoke(new Action(() => listBox8.Items.Add(z)));


and for the first problem my simple task looks like:
Yes, i have a Delay for 5 Seconds for the Second Task, but the nonce is to small.. I was thinking i can fix the "nonce small" with a small delay from 5-60 Seconds, but thats not helpfull :s how far must the time be apart to the second task? 

And yes, i get the "small nonce error" only after starting 2 or more Tasks! With ONE Task and ONE client.Start(); i have no nonce small error...
Its what you say, i call multiple client.Start(); in seperate tasks with everyone have a later delay, but the nonce is to small ^^



        async Task SimpleSecondTask(CancellationToken cts)
        {
            await Task.Delay(5000);
            string KEY = ("xxx");
            string SECRET = ("xxx");
            var options = new BitfinexSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(KEY, SECRET)
            };

            var client = new BitfinexSocketClient(options);
            var tickerSub = await client.SubscribeToTickerUpdates("tBTCEUR", data =>
            {
                string z = (string.Format("{0}", data[0].BidSize));
                Invoke((Action)delegate { listBox8.Items.Clear(); });
                listBox8.Invoke(new Action(() => listBox8.Items.Add(z)));

                AppendTextBox("Ticker BTC/EUR Update");
            });
                    client.Start();

            while (!cts.IsCancellationRequested)
            {
                await Task.Delay(100);
                if (cts.IsCancellationRequested)
                    client.Stop();
                break;
            }
        }

**Comment by Shipolia** [comment]
@Jkorf  No Problem and Thank you for fixing the second error :)
Maybe that helps you to solve the problem better, error show after this simple code:

                string z = (string.Format("{0}", data[0].BidSize));
                Invoke((Action)delegate { listBox8.Items.Clear(); });
                listBox8.Invoke(new Action(() => listBox8.Items.Add(z)));


and for the first problem my simple task looks like:
Yes, i have a Delay for 5 Seconds for the Second Task, but the nonce is to small.. I was thinking i can fix the "nonce small" with a small delay from 5-60 Seconds, but thats not helpfull :s how far must the time be apart to the second task? 

And yes, i get the "small nonce error" only after starting 2 or more Tasks! With ONE Task and ONE client.Start(); i have no nonce small error...
Its what you say, i call multiple client.Start(); in seperate tasks with everyone have a later delay, but the nonce is to small ^^



        async Task SimpleSecondTask(CancellationToken cts)
        {
            await Task.Delay(5000);
            string KEY = ("xxx");
            string SECRET = ("xxx");
            var options = new BitfinexSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(KEY, SECRET)
            };

            var client = new BitfinexSocketClient(options);
            var tickerSub = await client.SubscribeToTickerUpdates("tBTCEUR", data =>
            {
                string z = (string.Format("{0}", data[0].BidSize));
                Invoke((Action)delegate { listBox8.Items.Clear(); });
                listBox8.Invoke(new Action(() => listBox8.Items.Add(z)));

                AppendTextBox("Ticker BTC/EUR Update");
            });
                    client.Start();

            while (!cts.IsCancellationRequested)
            {
                await Task.Delay(100);
                if (cts.IsCancellationRequested)
                    client.Stop();
                break;
            }
        }

**Comment by JKorf** [comment]
Can you try the new version? I changed some things. Also instead of creating a new client for each subscription, you can just create 1 client and use it for multiple tickers right?

**Comment by kingchenc** [comment]
Thanks :+1:   @JKorf the new version works very fine, after 1 hour testing with multiple tasks/pair i have no error!
The other fix for "small nonce" is too fixed :)

**Comment by Shipolia** [comment]
Thanks :+1:   @JKorf the new version works very fine, after 1 hour testing with multiple tasks/pair i have no error!
The other fix for "small nonce" is too fixed :)

**Comment by JKorf** [comment]
Great :)
I'll close this issue then, let me know if you have any problems
