### ISSUE TITLE
Add Calc Available Balance from v2 rest api

### ISSUE THREAD

**Issue by albiezZz** [JKorf/Bitfinex.Net#21]
Hi,

Could you add Calc Available Balance from the v2 rest api? The available balance is always null in the v2 wallet updates (see issue https://github.com/bitfinexcom/bitfinex-api-node/issues/321 from bitfinex). 

At the moment I think it is not possible to get the available balance any other way.

**Comment by JKorf** [comment]
I've added the function, it's in the latest version (v1.0.9)
