### ISSUE TITLE
| Error | Deserialize Unknown Exception: Object reference not set to an instance of an object.. On GetTradeHistory

### ISSUE THREAD

**Issue by sblanchard** [JKorf/Bitfinex.Net#22]
var tempHistory =
                client.GetTradeHistory("tBTCUSD", DateTime.Now.ToUniversalTime().AddDays(-5), DateTime.Now.ToUniversalTime(), 100); or any variation of this I get this in the error object of the result

{4: Error deserializing data: Deserialize Unknown Exception: Object reference not set to an instance of an object.. Received data: [[252952940,"tBTCUSD",1527924973000,12901084933,0.03156876,7666.9,null,null,null,-0.00006314,"BTC"],[252951652,"tBTCUSD",1527924776000,12900995488,0.00477249,7670.1,null,null,null,-0.00000954,"BTC"],[252934984,"tBTCUSD",1527922910000,12900002077,-0.0003054,7658,null,null,null,-0.00467751,"USD"],[252934758,"tBTCUSD",1527922893000,12899973746,0.3869,7658.7,null,null,null,-5.92630206,"USD"],[252927963,"tBTCUSD",1527922562000,12899759854,-0.3865946,7651.3,null,null,null,-5.91590253,"USD"],[252926862,"tBTCUSD",1527922546000,12899737779,0.0000571,7630.5,null,null,null,-0.0008714,"USD"],[252923315,"tBTCUSD",1527922518000,12898670820,-0.3743,7595.5,null,null,null,-2.84299565,"USD"],[252911319,"tBTCUSD",1527919925000,12898597891,0.3742429,7491.5,null,null,null,-5.60728137,"USD"],[252909305,"tBTCUSD",1527919836000,12891715880,-0.3748,7476.05004176,null,null,null,-5.60404711,"USD"],[252863064,"tBTCUSD",1527901152000,12891499578,0.3748,7456.4,null,null,null,-5.58931744,"USD"],[252861654,"tBTCUSD",1527901094000,12890631716,-0.3871,7470.7,null,null,null,-5.78381594,"USD"],[252857537,"tBTCUSD",1527899271000,12890599468,0.3871,7513.6,null,null,null,-5.81702912,"USD"],[252857518,"tBTCUSD",1527899263000,12890595080,0.1818,7513.54525316,null,null,null,-2.73192505,"USD"],[252857024,"tBTCUSD",1527899192000,12890550352,-0.1818,7500.7,null,null,null,-2.72725452,"USD"]]}

**Comment by sblanchard** [comment]
Perhaps the fix...in BoolToIntConverter.cs check for null

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            return reader.Value != null && reader.Value.ToString() == "1";
        }

**Comment by JKorf** [comment]
Hi, that is indeed the problem. The boolean is null. I'll release a new version tomorrow.

**Comment by JKorf** [comment]
Is fixed in the latest version (v1.0.10)
