### ISSUE TITLE
Problem with duplicates when subscribing to trades after SocketClient is started

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#26]
If I start the SocketClient and then try to subscribe to trades I get an exception:

```Error in processing loop. System.InvalidOperationException, Sequence contains more than one matching element,    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: {"event":"subscribed","channel":"trades","chanId":30,"symbol":"tBCHUSD","pair":"BCHUSD"}```

The client expects there to only be one subscription result which would be correct. I will investigate myself and see if I can open a PR.

Will be using this library extensively in all our G&H apps moving forward, so would be nice if we could start a Discord or something where we could discuss more frequently instead of opening issues everytime? (Just a suggestion)

**Comment by JKorf** [comment]
What version did this happen in? Can you see if this still happens on the latest release?

**Comment by NektoDron** [comment]
It still happens

**Comment by NektoDron** [comment]
There are no errors, but trades are duplicated sometimes.

**Comment by JKorf** [comment]
Hi, I've done some work on the socket client. Can you update to the latest version and see if it still happens? If it does, please provide the log output after putting LogVerbosity on Info or Debug.

**Comment by henningms** [comment]
It seems to work fine now :)
