### ISSUE TITLE
Invalid dependencies in the Bitfinex.Net 1.0.11

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#27]
Unable to resolve dependencies. 'CryptoExchange.Net 0.0.27' is not compatible with 'Bitfinex.Net 1.0.11 constraint: CryptoExchange.Net (= 0.0.25)'.

**Comment by JKorf** [comment]
Hi, I assume you also use either Bittrex.NET or Binance.NET (or both). These libraries had updated CryptoExchange.Net to version 0.0.27, while Bitfinex.NET still required 0.0.25. I've updated Bitfinex.NET to the latest version and it should match again with the latest version. Sorry for the inconvenience.
