### ISSUE TITLE
Order status "Active" instead of "Executed"

### ISSUE THREAD

**Issue by Espleth** [JKorf/Bitfinex.Net#3]
var result = await client.GetOrderHistoryAsync("tBTCUSD");
foreach (var order in result.Data)
{
    Console.WriteLine(order.Status.ToString()); // all orders are active
}

**Comment by JKorf** [comment]
Hi, thanks for letting me know. Could you paste the returned data from the call? If you get the latest version (0.0.4) and put the log verbosity on Debug the returned data will be logged.

**Comment by Espleth** [comment]
0.0.4 and 0.0.5:

07:12:09:508 | Debug | Data returned: [[9512596861,null,78948879914,"tBTCUSD",1521410149000,1521410158000,0,0.00490202,"MARKET",null,null,null,null,"EXECUTED @ 8159.7(0.0)",null,null,8139.2,8159.7,0,0,null,null,null,0,0,null,null,null,null,null,null,null],[9512596826,null,78948622126,"tBTCUSD",1521410149000,1521410158000,0,0.00493297,"MARKET",null,null,null,null,"EXECUTED @ 8159.8(0.0)",null,null,8139.2,8159.8,0,0,null,null,null,0,0,null,null,null,null,null,null,null]]

order.Status still Active

**Comment by JKorf** [comment]
Thanks, the problem was I wasn't expecting the ' @ xxx' part in the status field. It should be fixed in version 0.0.6!
