### ISSUE TITLE
v2 api Trades call doesn't work

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#30]
I see what
https://api.bitfinex.com/v2/trades/btcusd/hist
returns nothing, but
https://api.bitfinex.com/v1/trades/btcusd
return last 50 trades.

Could you add v1 call instead v2?

**Comment by JKorf** [comment]
Hi, the V2 api is a bit more picky when it comes to input I guess. If works when you input tBTSUSD like so:
https://api.bitfinex.com/v2/trades/tBTCUSD/hist
I've added a check to automatically rewrite the symbol to this format in the new version (v1.0.13)
