### ISSUE TITLE
Order Subscription - status deserrialization error

### ISSUE THREAD

**Issue by ciottied** [JKorf/Bitfinex.Net#32]
Hi.

When I manually close positions on margin account (to reset positions opened by Trading system I'm developing/testing)  BitFinex.NET states (in immediate window) : 
```
Couldn't deserialize order status: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 6123.96104092(-0.07139999)
Couldn't deserialize order status: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 6123.96104092(-0.07139999)
Couldn't deserialize order status: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 458.76(-0.7182)
Couldn't deserialize order status: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 458.76(-0.7182)
```
Take the first: I manually closed a position of 0.0714 tBTCUSD.  Bitfinex system raises an error for insufficient balance (a bitfinex bug, in my opinion) and closes 0.07139999 tBTCUSD keeping the rest as trading fee.
But BitFinex.NET OrderUpdate Subscription is not able to deserialize message.

**Comment by JKorf** [comment]
To be honest, the Bitfinex API is pretty bad regarding an order status. I'm trying to parse the order status we receive from Bitfinex as a string to an enum to make it easier for clients to check what the status is without having to interpret the string. Bitfinex however tries to make this as hard as posible by sending strings like `INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 6123.96104092(-0.07139999)`...
I guess this one should map to Partially Filled, so I'll see if I can fix that.

**Comment by ciottied** [comment]
Agree on Bitfinex and Cryptoworld in general.
Everything appears to be tied together in some way.
Yes: I guess the correct mapping is partially filled.

Regards.

edc

**Comment by JKorf** [comment]
I've pushed a new version (v1.0.16) which should have this fixed, also added a StatusString property which maps to the original status bitfinex send. Let me know if there are any other problems.
