### ISSUE TITLE
Problem to subscribe to "bchbtc"

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#34]
version of library is latest.

18:13:36.60[46]DEBUG:[bitfinex] API: 2018/06/28 18:13:36:579 | Warning | No data received for 15 seconds, restarting connection
18:13:36.63[30]ERROR:AfterConnect: 
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeAndWait>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeToTickerUpdates>d__79.MoveNext()

**Comment by NektoDron** [comment]
I've tried to use "tbtcusd", but it doesn't work.

**Comment by NektoDron** [comment]
works fine with "btcusd"

**Comment by JKorf** [comment]
Sorry I'm a bit confused, subscribing doesn't work for what data? The error you pasted here apparently happened after not receiving data for 15 seconds, which seems to me is a different problem than not being able to subscribe?

**Comment by NektoDron** [comment]
Yes, subscribing doens't work for "bchbtc" but works fine for "btcusd", "ethusd", "ethbtc".

**Comment by JKorf** [comment]
Are you using the latest version? And what method are you using with what parameters? SubscribeToTradeUpdates, SubscribeToTickerUpdates etc. I tried some things but it seems to work fine for me.

**Comment by NektoDron** [comment]
It's works fine
