### ISSUE TITLE
Getting balance

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Bitfinex.Net#37]
Hi, thanks for the work with your APIs.

I'm having an issue using the bitfinex API getting balance. Why is the function asking for a side (buy or sell) and rate? We are just looking for symbol balances?
thanks

![image](https://user-images.githubusercontent.com/30062459/42201214-ce9db03e-7e64-11e8-8201-3657cf437d83.png)

**Comment by JKorf** [comment]
Hi, you're looking for the GetWallets method, it returns an array of symbol balances. 
The GetAvailableBalance method is used to calculate the available balance for an offer/order: https://docs.bitfinex.com/v2/reference#rest-auth-calc-bal-avail

**Comment by muteddisk** [comment]
thanks for the quick answer bud. Keep up the great works
