### ISSUE TITLE
Multithreading: Server returned an error: ["error",10114,"nonce: small"]

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#39]
Hi again,

I get a lot of these `nonce: small` errors on startup. I'm thinking it's due to me issuing subscriptions at the same time due to multi-threading (I load up my trading pairs asynchronously which in turn issues subscriptions).

Can we add a lock or something to prevent this if I'm not being weird in the way I want to utilize the client 😅 

```
2018/07/03 09:47:40:458 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:459 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:537 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:538 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:602 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:604 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:635 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:644 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:656 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:662 | Warning | Server returned an error: ["error",10114,"nonce: small"]
2018/07/03 09:47:40:685 | Warning | Server returned an error: ["error",10114,"nonce: small"]
```

**Comment by JKorf** [comment]
You're using a separate client for each subscription? Can you also see in the logging that the same nonce gets send? It gets send in the auth message at the start of the connection which gets logged when you put verbosity on Debug.

**Comment by henningms** [comment]
I'm using the same client (one Rest and one Socket). So my ViewModel goes through all my trading pairs and issue commands to the client to subscribe to updates via the SocketClient and fetch history using the rest client. This is done in parallel

**Comment by JKorf** [comment]
Okay, so the nonce is actually threadsafe. It increases by 1 in a lock every time it gets called. However, because you're sending the requests in parallel to the server there is no telling in what sequence they will arrive.
You might send Request 1,2,3 in parallel and they might arrive at the server in the order 2,3,1. You will then get an error about the nonce for request 1 since it has the lowest nonce but is received later than request 2 and 3. 
I'm not sure there is anything I can do to prevent this.
