### ISSUE TITLE
GetOrderBook returns error "10020 - prec: invalid"

### ISSUE THREAD

**Issue by maramzin** [JKorf/Bitfinex.Net#4]
... GetUrl(FillPathParameter(OrderBookEndpoint, symbol, precision.ToString()) ... <<< makes endpoint 'book/tETHUSD/**PrecisionLevel0**' instead of the correct value 'book/tETHUSD/**P0**'

**Comment by JKorf** [comment]
Hi, thanks for letting me know. It's fixed in the latest version (0.0.4)
