### ISSUE TITLE
Will BitfinexSocketClient's ProcessSending() and ProcessData() wait a maximum of 100ms?

### ISSUE THREAD

**Issue by GitteryCoder** [JKorf/Bitfinex.Net#41]
Looking at the code, I see this:
```
private void ProcessSending()
{
    while (running)
    {
        while (toSendMessages.TryTake(out string data, TimeSpan.FromMilliseconds(100)))
        {
            log.Write(LogVerbosity.Debug, "Sending " + data);
            socket.Send(data);
        }
    }
}
```
and 
```
private void ProcessData()
{
    while (running)
    {
        var received = receivedMessages.TryTake(out string dequeued, TimeSpan.FromMilliseconds(100));
        if (!received)
   ...
```

Will the TryTake(x, 100ms) cause delays to PlacingOrder and receiving market data?

**Comment by JKorf** [comment]
Hi,

It won't since these are 2 different tasks:
https://github.com/JKorf/Bitfinex.Net/blob/9342cb20c36100ebef896fb8866ff5fd802dd112/Bitfinex.Net/BitfinexSocketClient.cs#L721-L722

**Comment by GitteryCoder** [comment]
Thanks. I was thinking that TryTake might take up to 100ms to process it but I am mistaken. The 100ms is just how long the TryTake will wait before it loops around and try again. If data does arrive while it is waiting, it will process it anyway (probably woken up by some OS synchronization primitives).

**Comment by JKorf** [comment]
Hi, sorry I slightly misunderstood your question. The TryTake will indeed try to pull something from the queue. If it can't within the given time it will return false and continue. It will return true and continue as soon as it is possible to do so (the moment something is actually in the queue).
