### ISSUE TITLE
Received unknown event type

### ISSUE THREAD

**Issue by andrzej-suwala** [JKorf/Bitfinex.Net#45]
Hi,
I'm getting below warning on 1.1 
```

2018-07-18 12:51:13:190 | Warning | Received unknown event type: [
  1531910700000,
  7387.1,
  7396.6,
  7396.7,
  7387.1,
  32.85067643
]
```
Subscription to candles doesn't work as expected.
On 1.0.19 everything works.

**Comment by JKorf** [comment]
Hi, that's my bad, something broke when I did some refactoring. I've just pushed a new version (v1.1.1) which resolves the issue.

**Comment by andrzej-suwala** [comment]
Great, thanks 👍
