### ISSUE TITLE
problem with parsing 'te' and 'tu' messages on 1.1.2

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#47]
11:08:43.11[154]DEBUG:[Bitfinex_v7] API: 2018/07/24 11:08:43:118 | Error | Error in processing loop. System.FormatException, Входная строка имела неверный формат.,    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   в CryptoExchange.Net.Converters.TimestampConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   в CryptoExchange.Net.Converters.ArrayConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   в Bitfinex.Net.Objects.SocketObjects.SubscriptionRegistration.Handle(BitfinexEventType type, JArray obj)
   в Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: [2,"te",[272098900,1532419722268,-0.1,7996.2]]
11:08:43.13[154]DEBUG:[Bitfinex_v7] API: 2018/07/24 11:08:43:136 | Error | Error in processing loop. System.FormatException, Входная строка имела неверный формат.,    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   в CryptoExchange.Net.Converters.TimestampConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   в CryptoExchange.Net.Converters.ArrayConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   в Bitfinex.Net.Objects.SocketObjects.SubscriptionRegistration.Handle(BitfinexEventType type, JArray obj)
   в Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: [2,"tu",[272098896,1532419722258,-0.4,7996.3]]

**Comment by JKorf** [comment]
Hi, there was a problem where user trades and symbol trades got mixed up, since they both use the "te"/"tu" codes. I fixed the issue and pushed a new version, should be available in a few minutes (v1.1.3)
