### ISSUE TITLE
Fatal exception when socket was closed

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#49]
03:46:18.78[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:18:786 | Warning | Received unknown event type: [
  8238.8,
  9.99188904,
  8240.9,
  27.31380111,
  -201.1,
  -0.0238,
  8236.8,
  34477.45553309,
  8469.2,
  8073
]
03:46:18.78[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:18:789 | Warning | Received unknown event type: [
  8238.8,
  9.99188904,
  8240.9,
  27.31380111,
  -201.1,
  -0.0238,
  8236.8,
  34477.45553309,
  8469.2,
  8073
]
03:46:18.79[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:18:790 | Warning | Received unknown event type: [
  8238.8,
  9.99188904,
  8240.9,
  27.31380111,
  -201.1,
  -0.0238,
  8236.8,
  34477.45553309,
  8469.2,
  8073
]
03:46:18.83[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:18:833 | Warning | Received unknown event type: [
  8238.8,
  9.99188904,
  8240.9,
  27.31380111,
  -201.1,
  -0.0238,
  8236.8,
  34477.45553309,
  8469.2,
  8073
]
03:46:27.47[304]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:27:473 | Info | Received status code 20051, going to reconnect the websocket
03:46:27.47[491]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:27:474 | Info | Received status code 20051, going to reconnect the websocket
03:46:33.74[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:33:742 | Warning | Received unknown event type: [
  8242.2,
  430.05947569,
  8242.3,
  11.74478501,
  -195.6,
  -0.0232,
  8242.3,
  34477.47787126,
  8469.2,
  8073
]
03:46:33.75[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:33:757 | Warning | Received unknown event type: [
  8242.2,
  430.05947569,
  8242.3,
  11.74478501,
  -195.6,
  -0.0232,
  8242.3,
  34477.47787126,
  8469.2,
  8073
]
03:46:33.76[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:33:760 | Warning | Received unknown event type: [
  8242.2,
  430.05947569,
  8242.3,
  11.74478501,
  -195.6,
  -0.0232,
  8242.3,
  34477.47787126,
  8469.2,
  8073
]
03:46:33.76[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:33:762 | Warning | Received unknown event type: [
  8242.2,
  430.05947569,
  8242.3,
  11.74478501,
  -195.6,
  -0.0232,
  8242.3,
  34477.47787126,
  8469.2,
  8073
]
03:46:42.47[304]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:474 | Warning | No data received for 15 seconds, restarting connection
03:46:42.52[491]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:529 | Warning | No data received for 15 seconds, restarting connection
03:46:42.86[257]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:868 | Info | Socket connection established
03:46:42.87[180]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:870 | Info | Socket connection established
03:46:42.87[75]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:870 | Info | 0 subscriptions to resend
03:46:42.87[186]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:870 | Info | 0 subscriptions to resend
03:46:42.87[186]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:872 | Info | Websocket version: 2, platform status: operational
03:46:42.87[75]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:875 | Info | Websocket version: 2, platform status: operational
03:46:42.96[75]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:960 | Info | Authentication successful
03:46:42.96[186]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:42:969 | Info | Authentication successful
03:46:43.18[304]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:43:188 | Info | Socket connection established
03:46:43.18[81]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:43:188 | Info | 0 subscriptions to resend
03:46:43.19[81]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:43:190 | Info | Websocket version: 2, platform status: operational
03:46:43.26[81]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:43:261 | Info | Authentication successful
03:46:43.27[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:43:272 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:46:48.75[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:48:752 | Warning | Received unknown event type: [
  8243.4,
  458.48980304,
  8243.5,
  9.62246263,
  -194.5,
  -0.0231,
  8243.4,
  34477.65954299,
  8469.2,
  8073
]
03:46:48.75[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:48:754 | Warning | Received unknown event type: [
  8243.4,
  458.48980304,
  8243.5,
  9.62246263,
  -194.5,
  -0.0231,
  8243.4,
  34477.65954299,
  8469.2,
  8073
]
03:46:48.78[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:48:783 | Warning | Received unknown event type: [
  8243.4,
  458.48980304,
  8243.5,
  9.62246263,
  -194.5,
  -0.0231,
  8243.4,
  34477.65954299,
  8469.2,
  8073
]
03:46:49.15[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:46:49:159 | Warning | Received unknown event type: [
  8243.4,
  458.48980304,
  8243.5,
  9.62246263,
  -194.5,
  -0.0231,
  8243.4,
  34477.65954299,
  8469.2,
  8073
]
03:47:04.05[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:04:058 | Warning | Received unknown event type: [
  8243.5,
  19.76097226,
  8246.1,
  14.78054756,
  -191.1,
  -0.0226,
  8246.8,
  34478.91350044,
  8469.2,
  8073
]
03:47:04.06[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:04:060 | Warning | Received unknown event type: [
  8243.5,
  19.76097226,
  8246.1,
  14.78054756,
  -191.1,
  -0.0226,
  8246.8,
  34478.91350044,
  8469.2,
  8073
]
03:47:04.07[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:04:079 | Warning | Received unknown event type: [
  8243.5,
  19.76097226,
  8246.1,
  14.78054756,
  -191.1,
  -0.0226,
  8246.8,
  34478.91350044,
  8469.2,
  8073
]
03:47:04.43[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:04:438 | Warning | Received unknown event type: [
  8243.5,
  19.76097226,
  8246.1,
  14.78054756,
  -191.1,
  -0.0226,
  8246.8,
  34478.91350044,
  8469.2,
  8073
]
03:47:19.62[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:19:624 | Warning | Received unknown event type: [
  8240.1,
  10.20073784,
  8241,
  15.66815979,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:19.62[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:19:626 | Warning | Received unknown event type: [
  8240.1,
  10.20073784,
  8241,
  15.66815979,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:19.62[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:19:628 | Warning | Received unknown event type: [
  8240.1,
  10.20073784,
  8241,
  15.66815979,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:19.65[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:19:653 | Warning | Received unknown event type: [
  8240.1,
  10.20073784,
  8241,
  15.66815979,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:34.70[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:34:708 | Warning | Received unknown event type: [
  8240.1,
  11.26025517,
  8240.2,
  10.09732421,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:34.71[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:34:712 | Warning | Received unknown event type: [
  8240.1,
  11.26025517,
  8240.2,
  10.09732421,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:34.71[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:34:716 | Warning | Received unknown event type: [
  8240.1,
  11.26025517,
  8240.2,
  10.09732421,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:47:34.71[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:47:34:718 | Warning | Received unknown event type: [
  8240.1,
  11.26025517,
  8240.2,
  10.09732421,
  -197.8,
  -0.0234,
  8240.1,
  34479.68118951,
  8469.2,
  8073
]
03:48:03.88[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:03:887 | Warning | Received unknown event type: [
  8240.1,
  16.91216406,
  8240.2,
  35.62725533,
  -197.7,
  -0.0234,
  8240.2,
  34480.34364177,
  8469.2,
  8073
]
03:48:03.88[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:03:887 | Warning | Received unknown event type: [
  8240.1,
  16.91216406,
  8240.2,
  35.62725533,
  -197.7,
  -0.0234,
  8240.2,
  34480.34364177,
  8469.2,
  8073
]
03:48:03.88[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:03:888 | Warning | Received unknown event type: [
  8240.1,
  16.91216406,
  8240.2,
  35.62725533,
  -197.7,
  -0.0234,
  8240.2,
  34480.34364177,
  8469.2,
  8073
]
03:48:03.90[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:03:909 | Warning | Received unknown event type: [
  8240.1,
  16.91216406,
  8240.2,
  35.62725533,
  -197.7,
  -0.0234,
  8240.2,
  34480.34364177,
  8469.2,
  8073
]
03:48:09.74[280]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:09:741 | Warning | No data received for 15 seconds, restarting connection
03:48:09.81[280]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:09:815 | Info | Resetting subscription requests
03:48:14.13[487]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:14:136 | Warning | No data received for 15 seconds, restarting connection
03:48:16.64[113]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:16:640 | Warning | No data received for 15 seconds, restarting connection
03:48:17.06[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:064 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:17.78[57]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:786 | Info | Socket connection established
03:48:17.78[23]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:788 | Info | 0 subscriptions to resend
03:48:17.78[23]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:788 | Info | Websocket version: 2, platform status: operational
03:48:17.87[23]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:878 | Info | Authentication successful
03:48:17.99[470]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:17:992 | Warning | No data received for 15 seconds, restarting connection
03:48:18.06[470]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:064 | Info | Resetting subscription requests
03:48:18.08[113]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:086 | Info | Socket connection established
03:48:18.09[470]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:091 | Info | 0 subscriptions to resend
03:48:18.09[470]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:091 | Info | Websocket version: 2, platform status: operational
03:48:18.18[470]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:183 | Info | Authentication successful
03:48:18.18[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:186 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:18.34[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:345 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:18.42[280]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:424 | Info | Socket connection established
03:48:18.42[252]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:424 | Info | 2 subscriptions to resend
03:48:18.43[487]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:433 | Info | Websocket version: 2, platform status: operational
03:48:18.49[252]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:497 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
03:48:18.50[487]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:508 | Info | Authentication successful
03:48:18.57[252]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:571 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TradesSubscriptionRequest
03:48:18.92[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:922 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:18.93[310]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:932 | Warning | No data received for 15 seconds, restarting connection
03:48:18.94[310]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:948 | Info | Resetting subscription requests
03:48:18.97[461]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:18:974 | Warning | No data received for 15 seconds, restarting connection
03:48:19.01[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:015 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:19.06[461]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:066 | Info | Resetting subscription requests
03:48:19.16[348]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:169 | Warning | No data received for 15 seconds, restarting connection
03:48:19.17[60]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:174 | Warning | No data received for 15 seconds, restarting connection
03:48:19.22[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:227 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:19.25[348]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:254 | Info | Resetting subscription requests
03:48:19.47[269]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:473 | Warning | Received unknown event type: [
  8237.7,
  15.75575569,
  8237.8,
  12.62684243,
  -200.1,
  -0.0237,
  8237.8,
  34494.17600044,
  8469.2,
  8073
]
03:48:19.49[86]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:498 | Warning | Received unknown event type: [
  8237.7,
  15.75575569,
  8237.8,
  12.62684243,
  -200.1,
  -0.0237,
  8237.8,
  34494.17600044,
  8469.2,
  8073
]
03:48:19.50[336]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:500 | Warning | Received unknown event type: [
  8237.7,
  15.75575569,
  8237.8,
  12.62684243,
  -200.1,
  -0.0237,
  8237.8,
  34494.17600044,
  8469.2,
  8073
]
03:48:19.68[596]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:682 | Warning | Received unknown event type: [
  8237.7,
  15.75575569,
  8237.8,
  12.62684243,
  -200.1,
  -0.0237,
  8237.8,
  34494.17600044,
  8469.2,
  8073
]
03:48:19.68[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:19:684 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:20.70[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:20:703 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:20.78[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:20:784 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:20.88[416]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:20:882 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:21.15[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:21:155 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:21.97[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:21:971 | Warning | Server returned an error: ["error",10114,"nonce: small"]
03:48:22.27[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:272 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.28[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:287 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.30[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:304 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.32[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:322 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.34[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:340 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.35[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:357 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.37[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:377 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.39[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:395 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.41[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:414 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.44[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:440 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.56[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:564 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.56[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:567 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.62[555]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:625 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.64[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:644 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.69[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:697 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.69[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:699 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.74[553]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:744 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]
03:48:22.84[2]FATAL:UnobservedTaskExceptio: 
System.AggregateException: При ожидании задачи или доступе к ее свойству исключения не были замечены исключения задачи. В результате незамеченные исключения были созданы повторно потоком завершения. ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Bitfinex.Net.BitfinexSocketClient.<SocketClosed>b__91_0()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
---> (Внутреннее исключение #0) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Bitfinex.Net.BitfinexSocketClient.<SocketClosed>b__91_0()
   в System.Threading.Tasks.Task.Execute()<---

03:48:22.84[554]DEBUG:[Bitfinex_v7] API: 2018/07/26 03:48:22:840 | Warning | Server returned an error: ["error", 11010, "ratelimit: error"]

**Comment by JKorf** [comment]
It seems like something wen't wrong before this logging already since you're getting 'Received unknown event type' messages. Do you have logging of when that started happening as well?

**Comment by NektoDron** [comment]
I've started testing already, thanks.
