### ISSUE TITLE
Trailing stop order

### ISSUE THREAD

**Issue by maramzin** [JKorf/Bitfinex.Net#5]
How to add a trailing stop order via Bitfinex.NET API? The current version of the PlaceOrder method allows to pass only one price: 
PlaceOrder(string symbol, OrderSide side, type, decimal amount, decimal price)

**Comment by JKorf** [comment]
Hi, I don't see a trailing price parameter in the API documentation (https://docs.bitfinex.com/v1/reference#rest-auth-new-order). Or should the `buy_price_oco` / `sell_price_oco` be used for that? Documentation isn't too clear. You can also place an order on Bitfinex using their websocket implementation which can be accessed by using the `BitfinexSocketClient` in Bitfinex.Net. That implementation offers a trailing price parameter as per documentation.
