### ISSUE TITLE
Specify timeframe?

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#50]
Is it possible to make the TimeFrame not an enum or have an overload where we can specify timeframe ourselves? Interested in e.g four hour but that's not an option through the enum.

**Comment by JKorf** [comment]
Nope, sorry. The candles are pre-calculated on the server, generating on the fly would be too expensive. This means only the time frames that Bitfinex have calculations for can be offered. These are the values offered in the TimeFrame enum

**Comment by henningms** [comment]
I understand. It's a limitation on the backend then. Thought you could specify any timeframe using the string format they use.
