### ISSUE TITLE
Bitfinex Withdrawals

### ISSUE THREAD

**Issue by dmorris99** [JKorf/Bitfinex.Net#51]
Hi @JKorf -- nice libraries :) I'm using your Bittrex lib, but noticed that those guys charge a lot for withdrawals to off-exchange wallets.

Any plans to add withdrawal support to your Bitfinex library? Apologies if I missed it, but can't see any methods to do that.

**Comment by JKorf** [comment]
Hi, I've just pushed a new version, v1.1.5 which has the withdraw method implemented.

**Comment by dmorris99** [comment]
Nice!! Thank you @JKorf 👍

**Comment by dmorris99** [comment]
@JKorf fyi -- I see this error when trying to upgrade: "You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

This is on vs.net 2017; I already have a reference to .NetStandard 2.0 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll) which I think the error is related to.

I have seen this before on a previous version of your library (or might have been the Bittrex nugget), and seems to be present on some machines, but not others. I suspect it is more a nugget/vs.net bug, but still very frustrating. 

I suspect if you could make .NetFramework "native" nuggets, this would make installation a lot easier for people.
