### ISSUE TITLE
Could not install package 'Bitfinex.Net 1.1.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### ISSUE THREAD

**Issue by dmorris99** [JKorf/Bitfinex.Net#53]
Driving me crazy. As I understand it, this should "just work" , adding via nugget to a 4.6.1 assembly.

Yet it does not.

Attempting to gather dependency information for package 'Bitfinex.Net.1.1.6' with respect to project 'qtd', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 8.79 sec
Attempting to resolve dependencies for package 'Bitfinex.Net.1.1.6' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Bitfinex.Net.1.1.6'
Resolved actions to install package 'Bitfinex.Net.1.1.6'
Retrieving package 'Bitfinex.Net 1.1.6' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/bitfinex.net/1.1.6/bitfinex.net.1.1.6.nupkg
  OK https://api.nuget.org/v3-flatcontainer/bitfinex.net/1.1.6/bitfinex.net.1.1.6.nupkg 1178ms
Installing Bitfinex.Net 1.1.6.
Install failed. Rolling back...
Package 'Bitfinex.Net.1.1.6' does not exist in project 'qtd'
Package 'Bitfinex.Net.1.1.6' does not exist in folder 'C:\scp\qtd\packages'
Executing nuget actions took 1.75 sec
Could not install package 'Bitfinex.Net 1.1.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:14.1458934
========== Finished ==========

**Comment by dmorris99** [comment]
Repro case: VS.NET 2017
File, New Project
Templates / Visual C# / Windows Classic Desktop / Console App (.NET Framework)
Nuggets / add: Bitfinex.net 
Expected: works, actual: !expected

Is my expectation wrong?! The crazy thing is that I've had this working before!

**Comment by JKorf** [comment]
Hi, the library is targeting .netstandard 2.0. This means 4.6.1 should support it. I've seen your error before and you should make sure that your Visual Studio is up to date with the latest updates. That should fix this.

**Comment by dmorris99** [comment]
Indeed. Thanks @jKorf I shall try updating.

**Comment by dmorris99** [comment]
Upgrading vs.net fixes this.
