### ISSUE TITLE
Add more connection properties/consolidate connection status

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#54]
Hi,

During the night and the major dump and pump it seems the client disconnected and were unable to resume connection and/or subscriptions properly.

Could we add a Connected property as well as a ConnectionStatusChanged event with an enum: Connecting, Connected, ConnectionLost, Resuming etc to simplify it a bit and easier to understand what's going on under the covers? If you're tracking subscriptions and it in the end fails, could we get an event for that as well? (Just thinking out loud here)

**Comment by JKorf** [comment]
Do you have any logging of it not being able to reconnect? The socket client does have a `State` property, as well as ConnectionLost and ConnectionRestored events.

**Comment by henningms** [comment]
Ah, indeed there is a State property lol. My bad. Not sure how I missed that. That will probably do. 

Don't have logs as of now. Will come back to you with that.
