### ISSUE TITLE
1.1.7 ObjectDisposed Exception

### ISSUE THREAD

**Issue by andrzej-suwala** [JKorf/Bitfinex.Net#55]
Hi,

After connection loss ObjectDisposed exception is thrown:

  w System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   w System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   w Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   w System.Threading.EventWaitHandle.Set()
   w CryptoExchange.Net.Implementation.BaseSocket.&amp;lt;&amp;gt;c__DisplayClass35_0.&amp;lt;Connect&amp;gt;b__1(Object o, EventArgs a)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w WebSocket4Net.WebSocket.FireClosed()
   w WebSocket4Net.WebSocket.OnClosed()
   w SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   w SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   w System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   w System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   w System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   w System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   w System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.ContextAwareResult.Complete(IntPtr userToken)
   w System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   w System.Net.Dns.ResolveCallback(Object context)
   w System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   w System.Threading.ThreadPoolWorkQueue.Dispatch()</StackTrace><ExceptionString>System.ObjectDisposedException: Bezpieczne dojście zostało zamknięte
   w System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   w System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   w Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   w System.Threading.EventWaitHandle.Set()
   w CryptoExchange.Net.Implementation.BaseSocket.&amp;lt;&amp;gt;c__DisplayClass35_0.&amp;lt;Connect&amp;gt;b__1(Object o, EventArgs a)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w WebSocket4Net.WebSocket.FireClosed()
   w WebSocket4Net.WebSocket.OnClosed()
   w SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   w SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   w System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   w System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   w System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   w System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   w System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.ContextAwareResult.Complete(IntPtr userToken)
   w System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   w System.Net.Dns.ResolveCallback(Object context)
   w System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   w System.Threading.ThreadPoolWorkQueue.Dispatch()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll

**Comment by JKorf** [comment]
Hi thanks for the report. Im not at home currently, back at monday. I'll look into it then. For now i'd suggest to use 1.1.6 if this is onworkable.

**Comment by andrzej-suwala** [comment]
The same on 1.1.6.
1.1.5 is working fine :)

**Comment by andrzej-suwala** [comment]
Well, 1.1.5 is sometimes throwing ObjectDisposed too, but I'm not sure what is causing it yet:

StackTrace:
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at CryptoExchange.Net.Implementation.BaseSocket.<>c__DisplayClass35_0.<Connect>b__1(Object o, EventArgs a)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Dns.ResolveCallback(Object context)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by andrzej-suwala** [comment]
2018-08-19 17:20:50:362 | Info | Socket connection established
2018-08-19 17:20:50:390 | Info | Websocket version: 2, platform status: operational
2018-08-19 17:20:50:396 | Info | 1 subscriptions to resend
2018-08-19 17:20:50:476 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.CandleSubscriptionRequest
The thread 0x17c8 has exited with code 0 (0x0).
The thread 0x24b0 has exited with code 0 (0x0).
The thread 0x1f8c has exited with code 0 (0x0).
The thread 0x3374 has exited with code 0 (0x0).
The thread 0x4fd0 has exited with code 0 (0x0).
The thread 0x5488 has exited with code 0 (0x0).
2018-08-19 17:22:18:185 | Warning | No data received for 15 seconds, restarting connection
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
2018-08-19 17:22:21:248 | Info | Resetting subscription requests
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
The thread 0x17ec has exited with code 0 (0x0).
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
2018-08-19 17:22:25:201 | Error | Socket error: SocketException - Nieznany host
2018-08-19 17:22:25:202 | Warning | Couldn't connect to socket

And here the exception fires:

 w System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   w System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   w Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   w System.Threading.EventWaitHandle.Set()
   w CryptoExchange.Net.Implementation.BaseSocket.&amp;lt;&amp;gt;c__DisplayClass35_0.&amp;lt;Connect&amp;gt;b__1(Object o, EventArgs a)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w WebSocket4Net.WebSocket.FireClosed()
   w WebSocket4Net.WebSocket.OnClosed()
   w SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   w SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   w System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   w System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   w System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   w System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   w System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.ContextAwareResult.Complete(IntPtr userToken)
   w System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   w System.Net.Dns.ResolveCallback(Object context)
   w System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   w System.Threading.ThreadPoolWorkQueue.Dispatch()</StackTrace><ExceptionString>System.ObjectDisposedException: Bezpieczne dojście zostało zamknięte
   w System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   w System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   w Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   w System.Threading.EventWaitHandle.Set()
   w CryptoExchange.Net.Implementation.BaseSocket.&amp;lt;&amp;gt;c__DisplayClass35_0.&amp;lt;Connect&amp;gt;b__1(Object o, EventArgs a)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w WebSocket4Net.WebSocket.FireClosed()
   w WebSocket4Net.WebSocket.OnClosed()
   w SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   w SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   w System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   w System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   w System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   w System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   w System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.ContextAwareResult.Complete(IntPtr userToken)
   w System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   w System.Net.Dns.ResolveCallback(Object context)
   w System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   w System.Threading.ThreadPoolWorkQueue.Dispatch()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll`

**Comment by JKorf** [comment]
Hi, I've found an issue which I think was causing your problems. I fixed it in the latest release v1.1.8 which should be available in a few minutes. Could you try that and let me know if that fixes your issue?

**Comment by andrzej-suwala** [comment]
Hi !

It looks like it's working :)
I'll be looking at it in longer time frame and will report if any issues occur.
Thank you !
