### ISSUE TITLE
SubscribeToTickerUpdates problem happens today

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#56]
After call SubscribeToTickerUpdates server sends error:

◢ | Error | {3: Server error: No subscription confirmation received} | CryptoExchange.Net.Objects.Error {CryptoExchange.Net.Objects.ServerError}

SubscribeToTradeUpdates and SubscribeToBookUpdates still work fine.

**Comment by JKorf** [comment]
Hi, it works for me locally, what parameter are you using? Did you change the SubscribeResponseTimout option?

**Comment by NektoDron** [comment]
Tiker id "bchbtc", All parameters are by default.

**Comment by NektoDron** [comment]
But the second try was successful...

**Comment by NektoDron** [comment]
13:48:10.45[65]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:434 | Info | Socket connection established
13:48:10.47[25]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:455 | Info | 4 subscriptions to resend
13:48:10.47[18]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:434 | Info | Websocket version: 2, platform status: operational
2018/08/20 13:48:10:519 | Info | Authentication successful
13:48:10.52[18]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:519 | Info | Authentication successful
2018/08/20 13:48:10:581 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
13:48:10.58[3]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:581 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
2018/08/20 13:48:10:670 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
13:48:10.67[12]DEBUG:[Bitfinex] API: 2018/08/20 13:48:10:670 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
13:48:10.88[1]DEBUG:MainWindow deactivated
The thread 0x4724 has exited with code 0 (0x0).
The thread 0x424c has exited with code 0 (0x0).
2018/08/20 13:48:25:676 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again
13:48:25.67[3]DEBUG:[Bitfinex] API: 2018/08/20 13:48:25:676 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again
2018/08/20 13:48:40:678 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again
13:48:40.67[51]DEBUG:[Bitfinex] API: 2018/08/20 13:48:40:678 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again
13:48:43.54[1]DEBUG:MainWindow deactivated
The thread 0x45d8 has exited with code 0 (0x0).
2018/08/20 13:48:55:681 | Error | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, tried 3 times. Resetting subscription and try to reconnect
13:48:55.68[3]DEBUG:[Bitfinex] API: 2018/08/20 13:48:55:681 | Error | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, tried 3 times. Resetting subscription and try to reconnect
2018/08/20 13:48:55:770 | Info | DC'd while resending subscriptions, resetting all
13:48:55.77[3]DEBUG:[Bitfinex] API: 2018/08/20 13:48:55:770 | Info | DC'd while resending subscriptions, resetting all
2018/08/20 13:48:55:825 | Info | Resetting subscription requests
13:48:55.82[50]DEBUG:[Bitfinex] API: 2018/08/20 13:48:55:825 | Info | Resetting subscription requests
2018/08/20 13:48:58:114 | Info | Socket connection established
2018/08/20 13:48:58:114 | Info | 4 subscriptions to resend
13:48:58.11[60]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:114 | Info | Socket connection established
2018/08/20 13:48:58:138 | Info | Websocket version: 2, platform status: operational
13:48:58.14[55]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:114 | Info | 4 subscriptions to resend
13:48:58.16[65]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:138 | Info | Websocket version: 2, platform status: operational
2018/08/20 13:48:58:205 | Info | Authentication successful
13:48:58.20[65]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:205 | Info | Authentication successful
2018/08/20 13:48:58:244 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
13:48:58.24[3]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:244 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
2018/08/20 13:48:58:330 | Warning | Received unknown event type: [
  0.085362,
  65.11819343,
  0.085372,
  78.87098682,
  -0.002462,
  -0.028,
  0.085362,
  3686.51217227,
  0.090124,
  0.08397
]
13:48:58.33[65]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:330 | Warning | Received unknown event type: [
  0.085362,
  65.11819343,
  0.085372,
  78.87098682,
  -0.002462,
  -0.028,
  0.085362,
  3686.51217227,
  0.090124,
  0.08397
]
2018/08/20 13:48:58:331 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
13:48:58.33[12]DEBUG:[Bitfinex] API: 2018/08/20 13:48:58:331 | Info | Successfuly (re)subscribed Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest
The thread 0x280c has exited with code 0 (0x0).
2018/08/20 13:49:13:335 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again
13:49:13.33[3]DEBUG:[Bitfinex] API: 2018/08/20 13:49:13:335 | Warning | Failed to (re)sub Bitfinex.Net.Objects.SocketObjects.TickerSubscriptionRequest: 3: Server error: No subscription confirmation received, trying again

**Comment by JKorf** [comment]
What do you mean the second try was successful? The logging says 4 subscriptions we're active that should be resubscribed upon reconnecting. As far as I can see during the first reconnection it fails to resubscribe all 4, thus it disconnects and reconnects to try again. Then again the 3rd resub fails. 

Can you confirm there we're 4 subscriptions running? Did it successfully reconnect after this logging?

**Comment by JKorf** [comment]
Can you try version 1.2.0?

**Comment by NektoDron** [comment]
All works fine
