### ISSUE TITLE
SubscribeToTradeUpdates give same trade twice

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#57]
Hi,

We've noticed that the same trade gets broadcasted twice through the SubscribeToTradeUpdates method. This is due to Bitfinex sending a 'te' signal and then a 'tu': `After a “te” message you receive shortly a “tu” message that contains the real trade “ID”.` 

The time between te and tu updates can be enough to let other trades so as a workaround we'd have to do logic to filter out IDs that's already been processed.

Have you noticed this and do you have any thoughts on how to best deal with this situation?

**Comment by JKorf** [comment]
Couldn't you just ignore the "te" messages and just process the "tu" messages since that has all the information?

**Comment by henningms** [comment]
I can't differentiate between te and tu from the client side. `BitfinexTradeSimple` only contains Amount, Price, Id and Timestamp. Right now I'm filtering out IDs as we go along, but not sure if that's the best way to go about it. 

Any thoughts from a client perspective? Maybe TradeSimple could contain an enum property that distinguishes the type. `tu` messages as I understand it from the documentation is the confirmation that it's a real trade.

**Comment by JKorf** [comment]
I see the problem. I've wrapped the data in a `BitfinexSocketEvent` object, same as some of the other account related subscriptions. That should you out. Version 1.2.1 should be available in a few minutes.
