### ISSUE TITLE
GetDailyPerformance method doesn't work

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#58]
2018/08/24 18:08:19:787 | Warning | Server returned an error: ["error",10020,"method: invalid"]
18:08:19.78[40]DEBUG:[Bitfinex] API: 2018/08/24 18:08:19:787 | Warning | Server returned an error: ["error",10020,"method: invalid"]

**Comment by JKorf** [comment]
Hi, correct, I found that as well. The API documentation says this:
`This endpoint is still under active development so you might experience unexpected behavior from it.`
So  probably not usable at the moment.
