### ISSUE TITLE
Very nicely laid out library. Could you add subscription to the raw order book ? Should be just a few lines I would hope

### ISSUE THREAD

**Issue by JTriggerFish** [JKorf/Bitfinex.Net#6]

**Comment by JKorf** [comment]
Hi, I'll look into it. It would be a few lines, if only Bitfinex didn't decide that the would use the same keys for different data. When subscribing to normal books it uses the 'book' channel key, and when subscribing to the raw books it also uses 'book'. But they return different data. I'll have to change some things to get it to work.

**Comment by JKorf** [comment]
I implemented this in the latest version, enjoy :)

Let me know if something isn't working

**Comment by JTriggerFish** [comment]
Lovely, thank you!
