### ISSUE TITLE
Received unknown event type

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#61]
There are spam in the log:
2018/09/27 20:25:04:426 | Warning | Received unknown event type: [
  0.085704,
  112.78014428,
  0.085758,
  205.91612124,
  0.004895,
  0.0607,
  0.085595,
  31306.52265418,
  0.091274,
  0.078335
]
20:25:04.42[123]DEBUG:[bitfinex] API: 2018/09/27 20:25:04:426 | Warning | Received unknown event type: [
  0.085704,
  112.78014428,
  0.085758,
  205.91612124,
  0.004895,
  0.0607,
  0.085595,
  31306.52265418,
  0.091274,
  0.078335
]
2018/09/27 20:26:14:505 | Warning | Received unknown event type: [
  2.5557,
  393.75584237,
  2.563,
  328.55708677,
  0.1898,
  0.0801,
  2.5593,
  3349.34989523,
  2.6802,
  2.3374
]
20:26:14.50[123]DEBUG:[bitfinex] API: 2018/09/27 20:26:14:505 | Warning | Received unknown event type: [
  2.5557,
  393.75584237,
  2.563,
  328.55708677,
  0.1898,
  0.0801,
  2.5593,
  3349.34989523,
  2.6802,
  2.3374
]
2018/09/27 20:26:14:521 | Warning | Received unknown event type: [
  558.72,
  87.78350938,
  558.89,
  169.46987984,
  32,
  0.0608,
  558.47,
  187515.72559057,
  589.99,
  505.55
]
20:26:14.52[123]DEBUG:[bitfinex] API: 2018/09/27 20:26:14:521 | Warning | Received unknown event type: [
  558.72,
  87.78350938,
  558.89,
  169.46987984,
  32,
  0.0608,
  558.47,
  187515.72559057,
  589.99,
  505.55
]
2018/09/27 20:26:14:540 | Warning | Received unknown event type: [
  0.085837,
  52.66181508,
  0.085902,
  48.11008599,
  0.00521,
  0.0646,
  0.08591,
  31306.65504858,
  0.091274,
  0.078335
]
20:26:14.54[123]DEBUG:[bitfinex] API: 2018/09/27 20:26:14:540 | Warning | Received unknown event type: [
  0.085837,
  52.66181508,
  0.085902,
  48.11008599,
  0.00521,
  0.0646,
  0.08591,
  31306.65504858,
  0.091274,
  0.078335
]

**Comment by NektoDron** [comment]
it has been raised after subscribe to updates for bcheth and bchusd.

**Comment by JKorf** [comment]
Can you find the logging where this started happening? Subscribing to these updates works for me.

**Comment by NektoDron** [comment]
It happens random for any pair if you have subscription for many pairs at one time.
I call "DS.m_socketApi.SubscribeToTickerUpdates(Security.Id, UpdateFinInfo).Result"

**Comment by NektoDron** [comment]
13:41:20.19[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:172 | Debug | Received message: [314,[6301,4,10.75854405]]
13:41:20.23[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:194 | Debug | Processing [314,[6310.3,2,-0.14552625]]
2018/10/11 13:41:20:240 | Debug | Processing [328,[6301.6,59.76669673,6301.7,21.53770051,-271.20376575,-0.0413,6301.7,36562.53281488,6639,6252]]
13:41:20.24[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:240 | Debug | Processing [328,[6301.6,59.76669673,6301.7,21.53770051,-271.20376575,-0.0413,6301.7,36562.53281488,6639,6252]]
2018/10/11 13:41:20:239 | Debug | Received message: [314,[6300.5,2,0.42872916]]
13:41:20.24[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:239 | Debug | Received message: [314,[6300.5,2,0.42872916]]
2018/10/11 13:41:20:243 | Debug | Processing [12501,[0.07165,193.90733671,0.071725,179.49881888,-0.006368,-0.0814,0.07183,12554.97272682,0.078512,0.070649]]
13:41:20.26[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:243 | Debug | Processing [12501,[0.07165,193.90733671,0.071725,179.49881888,-0.006368,-0.0814,0.07183,12554.97272682,0.078512,0.070649]]
2018/10/11 13:41:20:264 | Debug | Received message: [314,[6300.2,2,0.90272686]]
2018/10/11 13:41:20:266 | Debug | Processing [12481,[2.2514,393.59503406,2.2589,396.50159475,-0.0224,-0.0099,2.249,2123.72600175,2.2961,2.1653]]
13:41:20.28[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:264 | Debug | Received message: [314,[6300.2,2,0.90272686]]
2018/10/11 13:41:20:288 | Debug | Received message: [314,[6298.8,1,0.19081505]]
13:41:20.28[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:266 | Debug | Processing [12481,[2.2514,393.59503406,2.2589,396.50159475,-0.0224,-0.0099,2.249,2123.72600175,2.2961,2.1653]]
13:41:20.31[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:288 | Debug | Received message: [314,[6298.8,1,0.19081505]]
2018/10/11 13:41:20:311 | Warning | Received unknown event type: [
  2.2514,
  393.59503406,
  2.2589,
  396.50159475,
  -0.0224,
  -0.0099,
  2.249,
  2123.72600175,
  2.2961,
  2.1653
]
13:41:20.33[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:311 | Warning | Received unknown event type: [
  2.2514,
  393.59503406,
  2.2589,
  396.50159475,
  -0.0224,
  -0.0099,
  2.249,
  2123.72600175,
  2.2961,
  2.1653
]
2018/10/11 13:41:20:335 | Debug | Processing [314,[6296.6,0,1]]
13:41:20.33[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:335 | Debug | Processing [314,[6296.6,0,1]]
2018/10/11 13:41:20:333 | Debug | Received message: [314,[6295.6,5,1.27898724]]
2018/10/11 13:41:20:337 | Debug | Processing [314,[6294.8,0,1]]
13:41:20.35[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:333 | Debug | Received message: [314,[6295.6,5,1.27898724]]
13:41:20.38[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:337 | Debug | Processing [314,[6294.8,0,1]]
2018/10/11 13:41:20:381 | Debug | Received message: [314,[6305.2,1,-2.9]]
2018/10/11 13:41:20:404 | Debug | Processing [314,[6310.3,0,-1]]
13:41:20.42[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:381 | Debug | Received message: [314,[6305.2,1,-2.9]]
13:41:20.44[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:404 | Debug | Processing [314,[6310.3,0,-1]]
2018/10/11 13:41:20:450 | Debug | Processing [314,[6301.6,21,22.7489997]]
13:41:20.45[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:450 | Debug | Processing [314,[6301.6,21,22.7489997]]
2018/10/11 13:41:20:449 | Debug | Received message: [314,[6305.7,1,-0.20918495]]
13:41:20.47[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:449 | Debug | Received message: [314,[6305.7,1,-0.20918495]]
2018/10/11 13:41:20:475 | Debug | Received message: [314,[6305.8,1,-0.63521337]]
13:41:20.47[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:475 | Debug | Received message: [314,[6305.8,1,-0.63521337]]
2018/10/11 13:41:20:477 | Debug | Received message: [314,[6307.4,2,-1.1]]
13:41:20.47[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:477 | Debug | Received message: [314,[6307.4,2,-1.1]]
2018/10/11 13:41:20:452 | Debug | Processing [314,[6301.5,2,0.9]]
2018/10/11 13:41:20:479 | Debug | Received message: [314,[6298.8,0,1]]
13:41:20.50[74]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:452 | Debug | Processing [314,[6301.5,2,0.9]]
13:41:20.52[93]DEBUG:[bitfinex] API: 2018/10/11 13:41:20:479 | Debug | Received message: [314,[6298.8,0,1]]

**Comment by NektoDron** [comment]
Hi, the problem is that the confirmation of the subscription may come later than the subscriptions messages.
I solved it by add some code to the method ProcessData of the class BitfinexSocketClient.
I added the second attempt to resolve data if it was not found.
This code should be added after line 1378
`                       if (channelReg == null)
                        {
                            Thread.Sleep(500); 
                            lock (confirmedRequestLock)
                                channelReg = confirmedRequests.SingleOrDefault(c => c.ChannelId == channelId);
                        }`

**Comment by NektoDron** [comment]
I see you made 1.2.5. It works fine. Issue can be closed.
