### ISSUE TITLE
confirmedRequests not properly handled

### ISSUE THREAD

**Issue by sobolevsv** [JKorf/Bitfinex.Net#62]
`confirmedRequests.Add(request);`  
is performed in a task, but 
`channelReg = confirmedRequests.SingleOrDefault(c => c.ChannelId == channelId);`
is checked in a thread which proccess received messages.
This often causes losing first messages.
I think you should handle confirmedRequests in one thread.

**Comment by JKorf** [comment]
Hi, you're right. I've moved the confirmation handling to the same thread in the latest version.
