### ISSUE TITLE
Remove item from subscriptionRequests, when subscription failed

### ISSUE THREAD

**Issue by ArtemKononov** [JKorf/Bitfinex.Net#64]
Hi! I am faced with strange behavior when subscribing to raw book updates (`BitfinexSocketClient.SubscribeToRawBookUpdates`). I tried to subscribe to 10 tickers; 9 attempts were successful, the 10th attempt failed (Success = false and Id = 0). In spite of the fact that the 10th attempt was unsuccessful, the failed request wasn't removed from the `subscriptionRequests` collection. 

As a result, I was faced with incorrect behavior within a reconnection process. 9 requests were successfully resubscribed, 1 request failed again (after 3 attempts to resubscribe). As a result, a reconnection process started again. 

This has been repeated many times. 

It seems that removing of a failed request from `subscriptionRequests` collection fit well. 
Could you advise me something?

**Comment by JKorf** [comment]
Hi, you're right. I was able to reproduce this issue, and fixed it in the latest version. Can you try with version 1.2.6?

**Comment by ArtemKononov** [comment]
It works fine. Thank you very much!
