### ISSUE TITLE
v2.0.1 System.MissingFieldException: 'Field not found: 'CryptoExchange.Net.BaseClient.BaseAddress'.'

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#65]
at any method call
Exception thrown: 'System.AggregateException' in mscorlib.dll
17:26:38.86[46]WARN :System.AggregateException: One or more errors occurred. ---> System.MissingFieldException: Field not found: 'CryptoExchange.Net.BaseClient.BaseAddress'.
   at Bitfinex.Net.BitfinexClient.GetUrl(String endpoint, String version)
   at Bitfinex.Net.BitfinexClient.<GetDailyPerformanceAsync>d__104.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Bitfinex.Net.BitfinexClient.GetDailyPerformance()
   at TSLab.Bitcoin.Bitfinex.BitfinexDS.Connecting() in C:\Projects\TSLab-dev2\providers\BTC-E.DataSource\Bitfinex\BitfinexDS.cs:line 126
---> (Inner Exception #0) System.MissingFieldException: Field not found: 'CryptoExchange.Net.BaseClient.BaseAddress'.
   at Bitfinex.Net.BitfinexClient.GetUrl(String endpoint, String version)
   at Bitfinex.Net.BitfinexClient.<GetDailyPerformanceAsync>d__104.MoveNext()<---

17:26:38.87[1]DEBUG:MainWindow deactivated
Exception thrown: 'System.MissingFieldException' in Bitfinex.Net.dll
Field not found: 'CryptoExchange.Net.BaseClient.BaseAddress'.

Exception thrown: 'System.AggregateException' in mscorlib.dll

**Comment by JKorf** [comment]
Can you verify you're on the latest version of CryptoExchange.Net?

**Comment by NektoDron** [comment]
Yes. I've update Bitfinex, Bittrex, Binance and CryptoExchange to the latest versions. Bitfinex doesn't work.

**Comment by JKorf** [comment]
Hm, I still suspect it is somehow still using the old version underwater. If you look at https://github.com/JKorf/CryptoExchange.Net/blob/d7600b5495a5cd6f422d6cb94056a3e068f072d1/CryptoExchange.Net/BaseClient.cs#L17 you can see that `BaseAddress` doest actually exists in the `BaseClient` class.

Maybe try to clear caches, clean solution and/or restart Visual Studio?

**Comment by NektoDron** [comment]
Already tried it, but it doesn't help. All of 4 dlls (Bitfinex, Bittrex, Binance and CryptoExchange) in the one folder. Bittrex and Binance  works fine, Bitfinex makes exception. May be it's a wrong dll at the nuget server?

**Comment by NektoDron** [comment]
https://www.screencast.com/t/UEdOCYKXeYAe
I've disassembled dll's from nuget folder

**Comment by JKorf** [comment]
My bad, I found the issue. It was referencing CryptoExchange.Net v2.0.0 instead of v2.0.2 like the others. I've pushed a fix which should be available in a few minutes. Sorry for the inconvenience!

**Comment by NektoDron** [comment]
2.02 works fine :)
