### ISSUE TITLE
BitfinexOrder duplicated array index

### ISSUE THREAD

**Issue by xjohnwu** [JKorf/Bitfinex.Net#66]
[ArrayProperty(13), JsonConverter(typeof(OrderStatusConverter))]
        public OrderStatus Status { get; set; }
        [ArrayProperty(13)]
        public string StatusString { get; set; }

StatusString should be 14. It doesn't matter on the first deserialization, but if you try to serialize and deserialize again, StatusString will be lost.

Could you please fix this issue ASAP? Thanks.

**Comment by xjohnwu** [comment]
Ah, sorry, I just checked Bitfinex documentation and StatusString should be 13. I will suggest you make Status as a derived field, e.g.
    [JsonIgnore]
    public OrderStatus Status { get => ConvertToOrderStatus(StatusString); }
where ConvertToOrderStatus() comes from OrderStatusConverter.

**Comment by JKorf** [comment]
Hi, yup that's probably a good suggestion. I've fixed it in version 2.0.3 which should be available in a few minutes.

**Comment by xjohnwu** [comment]
>           Hi, yup that's probably a good suggestion. I've fixed it in version 2.0.3 which should be available in a few minutes.

Wow, that's quick! Thanks a lot mate :)

**Comment by xjohnwu** [comment]
Ah, sorry, I should probably have mentioned earlier. The same issue exists for all classes that use JsonConverter(typeof(OrderStatusConverter)). You might want to fix them all :)

**Comment by xjohnwu** [comment]
I love your latest 2.0.3 update and all the changes :)
