### ISSUE TITLE
Proxy: unable to set username and password

### ISSUE THREAD

**Issue by evgenypolushkin** [JKorf/Bitfinex.Net#70]
It is not possible to somehow set the username and password when using a proxy

**Comment by evgenypolushkin** [comment]
I will explain. Bitfayneks constantly increases the limit rate. In such conditions it is impossible to work quickly with the exchange, the use of a proxy is required. This is critically important.

**Comment by JKorf** [comment]
Hi, if you update to the latest CryptoExchange version (2.0.10) you should be able to pass a username/password to the proxy. This is (for now) only available for the rest client. Let me know if this helps.
