### ISSUE TITLE
Deserialize error when cancelling trailing market and on placing trailing market, even tho both action are succesful..

### ISSUE THREAD

**Issue by DrPennis** [JKorf/Bitfinex.Net#72]
11/01/2019 15:03:17  Error deserializing data: Deserialize JsonSerializationException: Error setting value to 'Type' on 'Bitfinex.Net.Objects.RestV1Objects.BitfinexPlacedOrder'.. Received data: {
  "id": 21370305884,
  "cid": 50585632894,
  "cid_date": "2019-01-11",
  "gid": null,
  "symbol": "eosusd",
  "exchange": "bitfinex",
  "price": "2.5482",
  "avg_execution_price": "0.0",
  "side": "buy",
  "type": "trailing stop",
  "timestamp": "1547215385.651436056",
  "is_live": true,
  "is_cancelled": false,
  "is_hidden": false,
  "oco_order": null,
  "was_forced": false,
  "original_amount": "41.63054279",
  "remaining_amount": "41.63054279",
  "executed_amount": "0.0",
  "src": "api",
  "order_id": 21370305884
}

**Comment by JKorf** [comment]
This should be fixed in the latest version
