### ISSUE TITLE
"Nonce is too small." when new order is trying to place

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#78]
08:57:52.68[114]DEBUG:[Bitfinex] NewOrder: btcusd:Bitfinex:Limit:True:3500::1:OrderType:Limit; ContainerId:0; PortfolioOrderId:350989756; TradeName:
08:57:52.88[22]DEBUG:[Bitfinex] API: 2019/02/14 08:57:52:888 | Warning | Server returned an error: {"message":"Nonce is too small."}

I found the same problem at forums and they decided to multiply unixtime by 1000 to resolve this problem.

**Comment by NektoDron** [comment]
2019/02/18 11:25:21:924 | Debug | Creating request for https://api.bitfinex.com/v2/auth/r/wallets
11:25:21.92[262]DEBUG:[битфайн] API: 2019/02/18 11:25:21:924 | Debug | Creating request for https://api.bitfinex.com/v2/auth/r/wallets
2019/02/18 11:25:21:935 | Debug | Sending POST signed request to https://api.bitfinex.com/v2/auth/r/wallets 
11:25:21.93[262]DEBUG:[битфайн] API: 2019/02/18 11:25:21:935 | Debug | Sending POST signed request to https://api.bitfinex.com/v2/auth/r/wallets 
2019/02/18 11:25:21:991 | Warning | Server returned an error: ["error",10114,"nonce: small"]
11:25:21.99[418]DEBUG:[битфайн] API: 2019/02/18 11:25:21:991 | Warning | Server returned an error: ["error",10114,"nonce: small"]

**Comment by NektoDron** [comment]
It happens if connection exists for 2-3 days without breaks. If it disconnects for 1 minute per day the this issue doesn't happen.

**Comment by JKorf** [comment]
I've adjusted the nonce calculation. Used to take the epoch timestamp the first time the nonce was needed and add 1 every time the nonce was needed after that. Looks like Bitfinex checks if the nonce isn't too far off the current epoch timestamp, so I've changed it to always take the current epoch timestamp and add 1 if it is the same as the last.

I've pushed version 2.0.7 which should be available in a few minutes. Let me know if that fixes the issue.

**Comment by NektoDron** [comment]
The newest version can't normally restore subscriptions.
I've lost the queue updates after some hours. The 2.0.4 worked fine.

17:42:24.94[210]DEBUG:[битфайн] API: 2019/02/18 17:42:24:943 | Info | Socket 1 failed to resubscribe resubscribed
17:42:27.31[217]DEBUG:[битфайн] API: 2019/02/18 17:42:27:312 | Info | Socket 2 reconnected after 00:00:05.3063010
17:42:27.70[57]DEBUG:[битфайн] API: 2019/02/18 17:42:27:699 | Info | Code 20051 received, reconnecting socket
17:42:27.76[57]DEBUG:[битфайн] API: 2019/02/18 17:42:27:761 | Info | Socket 7 Connection lost, will try to reconnect after 00:00:05
17:42:27.83[90]DEBUG:[битфайн] API: 2019/02/18 17:42:27:830 | Info | Socket 2 closed
17:42:28.98[36]DEBUG:[битфайн] API: 2019/02/18 17:42:28:982 | Info | Socket 5 reconnected after 00:00:05.2945830
17:42:29.04[36]DEBUG:[битфайн] API: 2019/02/18 17:42:29:049 | Info | Socket 5 successfully resubscribed
17:42:29.76[217]DEBUG:[битфайн] API: 2019/02/18 17:42:29:762 | Info | Socket 2 failed to resubscribe resubscribed
17:42:30.23[75]DEBUG:[битфайн] API: 2019/02/18 17:42:30:234 | Info | Code 20051 received, reconnecting socket
17:42:30.23[90]DEBUG:[битфайн] API: 2019/02/18 17:42:30:235 | Info | Code 20051 received, reconnecting socket
17:42:30.29[75]DEBUG:[битфайн] API: 2019/02/18 17:42:30:296 | Info | Socket 3 Connection lost, will try to reconnect after 00:00:05
17:42:30.30[90]DEBUG:[битфайн] API: 2019/02/18 17:42:30:300 | Info | Socket 4 Connection lost, will try to reconnect after 00:00:05
17:42:33.05[37]DEBUG:[битфайн] API: 2019/02/18 17:42:33:059 | Info | Socket 7 reconnected after 00:00:05.2965360
17:42:35.43[35]DEBUG:[битфайн] API: 2019/02/18 17:42:35:437 | Info | Socket 4 reconnected after 00:00:05.1373665
17:42:35.50[35]DEBUG:[битфайн] API: 2019/02/18 17:42:35:507 | Info | Socket 4 successfully resubscribed
17:42:35.59[233]DEBUG:[битфайн] API: 2019/02/18 17:42:35:594 | Info | Socket 3 reconnected after 00:00:05.2955595
17:42:35.67[233]DEBUG:[битфайн] API: 2019/02/18 17:42:35:670 | Info | Socket 3 successfully resubscribed
17:42:43.05[37]DEBUG:[битфайн] API: 2019/02/18 17:42:43:058 | Info | Socket 7 failed to resubscribe resubscribed

**Comment by NektoDron** [comment]
> I've pushed version 2.0.7 which should be available in a few minutes. Let me know if that fixes the issue.
It's not worked. After 20-30 hours of work, exceptions begin.

**Comment by JKorf** [comment]
I've asked Bitfinex support why this would happen, waiting for their response. One thing I could think of is if you're placing 2 order at the same time Bitfinex might receive the 2nd order with a higher nonce before the first order with a lower nonce, which could lead to this error. Are you placing multiple orders at the same time?

**Comment by NektoDron** [comment]
No, It happens when orders aren't placed for hours and then it's trying to place.

**Comment by JKorf** [comment]
This is the response from the Bitfinex team:
`The only requirement for the nonce is that it has a larger value than the previous nonce. The code used to generate a nonce used looks like it would produce a larger number each time, but perhaps a greater nonce was inadvertantly entered at some point. Is there anything else in the code that may conflict with this method of generating a nonce? Are there multiple processes running using the same API key? Due to the fact that the nonce needs to be increasing each time, if you are running multiple concurrent integrations it is recommended to use a different API key for each one.`

The nonce that is generated in the library is by design bigger after each call. There should be no reason why it would suddenly not be bigger than the last. Do you maybe run some other application or 3rd party app which uses the same API key? The nonce is bound to the API key, so if you're using it for multiple purposes they might interfere with eachother.

**Comment by NektoDron** [comment]
Ok, I understood. I've used one apikey on several computers because Bitfinex sends one apikey per user.
