### ISSUE TITLE
after a couple of hours, orderbook stops updating

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#79]
I subscribe by call SubscribeToBookUpdates and all works fine. But then stops working, without any notification.

I see only these strings:
13:48:19.56[163]DEBUG:[Bitfinex] API: 2019/02/21 13:48:19:569 | Info | Socket 437 Connection lost, will try to reconnect
13:48:24.93[174]DEBUG:[Bitfinex] API: 2019/02/21 13:48:24:937 | Info | Socket 437 reconnected after 00:00:05.3687127
13:48:25.02[174]DEBUG:[Bitfinex] API: 2019/02/21 13:48:25:025 | Info | Socket 437 successfully resubscribed
13:52:39.73[180]DEBUG:[Bitfinex] API: 2019/02/21 13:52:39:739 | Warning | No data received for 00:00:30, reconnecting socket
13:52:44.69[32]DEBUG:[Bitfinex] API: 2019/02/21 13:52:44:694 | Warning | No data received for 00:00:30, reconnecting socket
13:52:44.74[133]DEBUG:[Bitfinex] API: 2019/02/21 13:52:44:743 | Info | Socket 437 Connection lost, will try to reconnect
13:52:49.69[37]DEBUG:[Bitfinex] API: 2019/02/21 13:52:49:698 | Info | Socket 466 Connection lost, will try to reconnect

**Comment by JKorf** [comment]
Judging from the logging the subscription is successfully resubscribed, but doesn't receive any data after resubscribing. What subscription method are you using with what parameters?

**Comment by NektoDron** [comment]
I'm using "socketApi.SubscribeToExchangeStateUpdates(Security.Id, UpdateExchange)"
And I takes from it queues and trades. The trades are updated always, but queues are stopped.

**Comment by JKorf** [comment]
The `SubscribeToExchangeStateUpdates` method is from the Bittrex API, not the Bitfinex API.
You're logging suggests an issue in the bitfinex lib though

**Comment by JKorf** [comment]
Is this still relevant?

**Comment by JKorf** [comment]
Closing, if you still have issues let me know. Note that there is also a order book implementation available now: `BitfinexSymbolOrderBook`.
