### ISSUE TITLE
Candles: Getting only 120 results at a time

### ISSUE THREAD

**Issue by andrzej-suwala** [JKorf/Bitfinex.Net#8]
Hi,

Using your great lib I can get only 120 results of historical candles, no matter what I put into
GetCandlesAsync params.
But using a direct link Bitfinex is responding with up to 1000 results.
https://api.bitfinex.com/v2/candles/trade:1m:tBTCUSD/hist?start=1514764800000&limit=1000&sort=1

I was trying to put:
-startTime=correct date, endTime=correct date 1000 minutes later, limit=null
-startTime=correct date, endTime=correct date 1000 minutes later, limit=1000
-startTime=correct date, endTime=null, limit=1000
-startTime=correct date, endTime=null, limit=null

Always GetCandlesAsync returns 120 candles at max.

I'm writing charting app, and trying to download some historical candles, back from 2017.01.01.
While Bitfinex is rate-limitting candles about 20 req/minute + 1 minute pause, it's a real pain to wait for more than 650k candles to download :)

Is it possible to get more then 120 results with your lib ?

Thank you !

**Comment by JKorf** [comment]
Hi,

The limit parameter in the call wasn't mapped correctly, so it always defaulted to 120. I've fixed it and checked, and it works for 1000 candles as well if you set the limit parameter!
