### ISSUE TITLE
Wrong OrderStatus

### ISSUE THREAD

**Issue by xjohnwu** [JKorf/Bitfinex.Net#81]
For the following status string

> CANCELED was: PARTIALLY FILLED @ 4104.2(0.0620667)

OrderStatusConverter interprets it as PartiallyFilled instead of Canceled. Could you please correct this logic to the following?

1. Split string with "was"
2. Split first part of string with "@"
3. Then use contains to decide order status

**Comment by JKorf** [comment]
Thanks for the report, is fixed in the latest version
