### ISSUE TITLE
BitfinexClient.GetTicker does not work

### ISSUE THREAD

**Issue by fiatsasia** [JKorf/Bitfinex.Net#82]
Defined endpoint of ticker in BitfinexClient.cs as "tickers" but defined  "pubticker" in Bitfinex site as below URL.

https://docs.bitfinex.com/v1/reference#rest-public-ticker

**Comment by JKorf** [comment]
Hi,
it is using the V2 api: https://docs.bitfinex.com/v2/reference#rest-public-tickers
What is the problem you're having?

**Comment by fiatsasia** [comment]
Thank you. I added prefix 't' in front of symbol, it works fine!
