### ISSUE TITLE
WebSocket API response does not contain channel-ID

### ISSUE THREAD

**Issue by fiatsasia** [JKorf/Bitfinex.Net#83]
WebSocket APIs return channel-ID when subscription is subscribed but pushed data C# class does not contain channel-ID.
This means my application subscribes multiple symbols by multiple requests with same callback handler, it could not identify which data arrived in my callback handler.

How could I identify channel-ID in my callback handler or does Bitfinex.Net manage channel-ID / callback handler mapping inside ?

**Comment by JKorf** [comment]
Hi, you're right. you can't currently know which data came from which subscription. However you can make a simple anonymous function wrapping your handler to which you can pass the data you need. For example:
````C#
        private static void SubscribeSymbol(IBitfinexSocketClient socketClient, string symbol)
        {
            socketClient.SubscribeToTickerUpdates(symbol, data => HandleTickerUpdate(symbol, data));

        }

        private static void HandleTickerUpdate(string symbol, BitfinexMarketOverview data)
        {
            Console.WriteLine($"{symbol} ticker: {data.LastPrice}");
        }
````

**Comment by fiatsasia** [comment]
Thank you for your advice. I will try anonymous handler.
