### ISSUE TITLE
The type or namespace name 'BitfinexMarketOverviewRest' could not be found

### ISSUE THREAD

**Issue by shotyme** [JKorf/Bitfinex.Net#84]
Hello,

I've just added the current nuget version of this lib to a test project and tried to run the code snippet of the readme.

I'm getting the error  'BitfinexMarketOverviewRest' could not be found. 

What could cause this error?

![12](https://user-images.githubusercontent.com/26322651/57166553-ddaf1000-6dfa-11e9-87de-1835d2b334e5.png)

**Comment by JKorf** [comment]
Hi, make sure you also have the object namespace included in your usings:
`using Bitfinex.Net.Objects;`
It should be in there.

**Comment by JKorf** [comment]
Assuming you've got it working by now. If not let me know.
