### ISSUE TITLE
BitfinexSocketClient to place a sell order?

### ISSUE THREAD

**Issue by mzhou2018** [JKorf/Bitfinex.Net#86]
i could simple place a buy order with the following code:
wsBitfinex.PlaceOrder(type: OrderType.ExchangeLimit, symbol:"tBTTUSD", priceTrailing: 0.0013586m, amount: 10000, price: 0.0013586m, clientOrderId: 341143 );

how can i place a sell order ? thank you.

**Comment by JKorf** [comment]
Hi, if I recall correctly passing a negative number will be interpreted as a sell, so something like:
wsBitfinex.PlaceOrder(type: OrderType.ExchangeLimit, symbol:"tBTTUSD", priceTrailing: 0.0013586m, amount: -10000, price: 0.0013586m, clientOrderId: 341143 );

**Comment by mzhou2018** [comment]
:) thank you.
