### ISSUE TITLE
Implement margin position functionality

### ISSUE THREAD

**Issue by astralcake** [JKorf/Bitfinex.Net#87]
Is it possible to close active positions (market sell or buy) with api? Thanks.

**Comment by JKorf** [comment]
Hi, this is currently not supported. Will leave this open though, I'll implement it somewhere in the coming days.

**Comment by astralcake** [comment]
Nice!

**Comment by JKorf** [comment]
Hi, I've added the missing methods in the latest version, however I wasn't able to test all of them. The calls should be correct, however the documentation of the returned data isn't always very elaborate on the Bitfinex api docs. Could you please let me know if your run into any issues and if the return data is correct?

**Comment by astralcake** [comment]
Ok, thanks!

**Comment by astralcake** [comment]
GetPositionHistory() returns:

Error deserializing data: Deserialize Unknown Exception: Can not convert Integer to DateTime.. Received data: [
  [
    "tBTCUSD",
    "CLOSED",
    0,
    12025,
    0,
    0,
    null,
    null,
    null,
    null,
    null,
    141310225,
    1561625331000,
    1561626593000,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  [
    "tLTCUSD",
    "CLOSED",
    0,
    142.70825972,
    0,
    0,
    null,
    null,
    null,
    null,
    null,
    141232515,
    1561316568000,
    1561326569000,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  [
    "tBTCUSD",
    "CLOSED",
    0,
    9137.9,
    0,
    0,
    null,
    null,
    null,
    null,
    null,
    141170542,
    1560930571000,
    1560950415000,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  [
    "tBTCUSD",
    "CLOSED",
    0,
    -17300899.230769228,
    0,
    0,
    null,
    null,
    null,
    null,
    null,
    141146063,
    1560715824000,
    1560871990000,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  [
    "tEOSUSD",
    "CLOSED",
    0,
    6.0678,
    0,
    0,
    null,
    null,
    null,
    null,
    null,
    141076105,
    1560102162000,
    1560454163000,
    null,
    null,
    null,
    null,
    null,
    null
  ]
]

**Comment by astralcake** [comment]
API v2 very strange at all: to close position we need to know it's id. But method GetActivePositions doesn't returns id. Okay, then we try GetPositionHistory and select Status == Active. But it returns only closed positions.

It seems like API v1 better for position managing.. Just my vision.

**Comment by astralcake** [comment]
Found solution. Ples check my PR.

**Comment by JKorf** [comment]
Thanks for taking the time to look into this, I've merged your PR and will release a new version shortly.

**Comment by JKorf** [comment]
Version v2.1.1 is ready for you to try

**Comment by JKorf** [comment]
I assume this is working correctly now, let me know if it doesn't.
