### ISSUE TITLE
System.MissingMethodException from CryptoExchange.Net when creating socket-client instance

### ISSUE THREAD

**Issue by TrustyDoge** [JKorf/Bitfinex.Net#93]
![Unbenannt](https://user-images.githubusercontent.com/48845663/64068575-4b006f80-cc3a-11e9-8cf6-0a53c8d49fa1.PNG)

I tried different versions of CryproExchange.Net and creating client with and without parameters: same error every time. 

System.MissingMethodException: 'Method not found: "Void CryptoExchange.Net.SocketClient.set_ContinueOnQueryResponse(Boolean)".'

I checked for the property-setter in question and to me it looks like it is there..
'protected' as usual for use in inherited class..
It never makes it inside your constructor before throwing the Exception in my code.

![Unbenannt2](https://user-images.githubusercontent.com/48845663/64068833-10003b00-cc3e-11e9-95b8-4c745051e798.PNG)

Big fan of your work. Great code.

**Comment by JKorf** [comment]
Hi, sorry for the late response, I missed the notification I guess..

I'm not sure why you're getting this, doing a clean install from nuget doesn't have this issue. I'd say its probably a caching issue of visual studio. Have you managed to fix it by now?
