### ISSUE TITLE
Trailingstops no longer work

### ISSUE THREAD

**Issue by stevewonderburg** [JKorf/Bitfinex.Net#96]
Bitfinex updated their V1 API to match their V2 denominations, trailingstop now requires to be written as:

"trailing-stop" instead of

"trailing stop" as shown here

`new KeyValuePair<OrderTypeV1, string>(OrderTypeV1.TrailingStop, "trailing stop"),`

![image](https://user-images.githubusercontent.com/42620621/68074670-e4b0de00-fd9d-11e9-97be-c9253c274d95.png)

Without this fix, any trailingstop is currently opened as a regular stop.

**Comment by JKorf** [comment]
Hi, thanks for the report. I've fixed it and pushed a new version.
