### ISSUE TITLE
avg_execution_price is always 0

### ISSUE THREAD

**Issue by behr0oz** [JKorf/Bitfinex.Net#98]
Hello,
When i place an order with market type the "avg_execution_price"  is always 0.
could you place check this out?

**Comment by JKorf** [comment]
Hi, I currently don't have funds on Bitfinex so it's a bit hard to test for me, but it is implemented as described in the API documentation. Could you maybe install te latest version of the CryptoExchange.Net library (3.0.1), put LogVerbosity on Debug in the client options and check the output for what data is actually returned from the server?

**Comment by behr0oz** [comment]
**Of course, here it is:**

> 2019/11/14 22:57:03:170 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: -, BaseAddress: https://api.bitfinex.com, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
> 2019/11/14 22:57:03:628 | Debug | Setting api credentials
> 2019/11/14 22:57:04:034 | Debug | Creating request for https://api.bitfinex.com/v1/order/new
> 2019/11/14 22:57:04:269 | Debug | Sending POST signed request to https://api.bitfinex.com/v1/order/new with request body {"amount":"12","exchange":"bitfinex","nonce":"1573772224036959","price":"0.2","request":"/v1/order/new","side":"buy","symbol":"XRPUSD","type":"market"}
> 2019/11/14 22:57:05:639 | Debug | Data received: {"id":34139118001,"cid":82645989018,"cid_date":"2019-11-14","gid":null,"symbol":"xrpusd","exchange":"bitfinex","price":"0.26872","avg_execution_price":"0.0","side":"buy","type":"market","timestamp":"1573772246.006738669","is_live":true,"is_cancelled":false,"is_hidden":false,"oco_order":null,"was_forced":false,"original_amount":"12.0","remaining_amount":"12.0","executed_amount":"0.0","src":"api","meta":null,"order_id":34139118001}

**After this when i call the GetOrder api for this order id the "avg_execution_price" parameter is filled.**

**Comment by JKorf** [comment]
Seems to be that the Bitfinex API simply doesn't return the information, so there isn't a lot I can do about that.
The wrapper is using the V1 API to place a new order since placing orders wasn't available at the time of making this wrapper on the V2 API. They've added it to V2 since then, and I'll refactor the PlaceOrder method to use V2 at some point. Maybe the V2 API will return the average price.

No timeline on that though.

**Comment by behr0oz** [comment]
Ok, thanks
